import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

/**
 * A single entry in chapters.json representing an initialized chapter/role combination.
 */
export interface ChapterEntry {
  lodge: string;
  chapter: string;
  role: string;
  dockerBuild: string;
  roleDir: string;
  targetDir?: string;
  agents: string[];
  createdAt: string;
  updatedAt: string;
}

/**
 * The top-level structure of chapters.json.
 */
export interface ChaptersJson {
  chapters: ChapterEntry[];
}

const CHAPTERS_JSON = "chapters.json";
const GITIGNORE = ".gitignore";
const GITIGNORE_CONTENT = `# Auto-generated by chapter CLI\n**/logs/\n`;

/**
 * Resolve the CLAWMASONS_HOME directory.
 * Reads from the CLAWMASONS_HOME environment variable; defaults to ~/.clawmasons.
 */
export function getClawmasonsHome(): string {
  const envValue = process.env["CLAWMASONS_HOME"];
  if (envValue) {
    return path.resolve(envValue);
  }
  return path.join(os.homedir(), ".clawmasons");
}

/**
 * Ensure the CLAWMASONS_HOME directory exists with a .gitignore.
 * Creates the directory and .gitignore if they don't exist. Safe to call multiple times.
 */
export function ensureClawmasonsHome(home: string): void {
  fs.mkdirSync(home, { recursive: true });

  const gitignorePath = path.join(home, GITIGNORE);
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, GITIGNORE_CONTENT, "utf-8");
  }
}

/**
 * Read and parse chapters.json from the CLAWMASONS_HOME directory.
 * Returns { chapters: [] } when the file doesn't exist.
 * Throws on malformed JSON.
 */
export function readChaptersJson(home: string): ChaptersJson {
  const filePath = path.join(home, CHAPTERS_JSON);
  if (!fs.existsSync(filePath)) {
    return { chapters: [] };
  }

  const content = fs.readFileSync(filePath, "utf-8");
  try {
    const data = JSON.parse(content) as ChaptersJson;
    if (!data.chapters || !Array.isArray(data.chapters)) {
      return { chapters: [] };
    }
    return data;
  } catch (err) {
    throw new Error(
      `Failed to parse ${filePath}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * Write chapters.json to the CLAWMASONS_HOME directory.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
export function writeChaptersJson(home: string, data: ChaptersJson): void {
  const filePath = path.join(home, CHAPTERS_JSON);
  const tmpPath = `${filePath}.tmp`;
  const content = JSON.stringify(data, null, 2) + "\n";
  fs.writeFileSync(tmpPath, content, "utf-8");
  fs.renameSync(tmpPath, filePath);
}

/**
 * Find a role entry in chapters.json by composite key (lodge, chapter, role).
 * Returns undefined if not found.
 */
export function findRoleEntry(
  home: string,
  lodge: string,
  chapter: string,
  role: string,
): ChapterEntry | undefined {
  const data = readChaptersJson(home);
  return data.chapters.find(
    (entry) =>
      entry.lodge === lodge &&
      entry.chapter === chapter &&
      entry.role === role,
  );
}

/**
 * Insert or update a role entry in chapters.json.
 * Matches by composite key (lodge, chapter, role).
 * If found, updates the existing entry's fields and sets updatedAt.
 * If not found, appends with both createdAt and updatedAt.
 */
export function upsertRoleEntry(home: string, entry: ChapterEntry): void {
  const data = readChaptersJson(home);
  const idx = data.chapters.findIndex(
    (existing) =>
      existing.lodge === entry.lodge &&
      existing.chapter === entry.chapter &&
      existing.role === entry.role,
  );

  if (idx >= 0) {
    data.chapters[idx] = {
      ...entry,
      createdAt: data.chapters[idx].createdAt,
      updatedAt: entry.updatedAt,
    };
  } else {
    data.chapters.push(entry);
  }

  writeChaptersJson(home, data);
}
