import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

/**
 * A single entry in chapters.json representing an initialized chapter/role combination.
 */
export interface ChapterEntry {
  lodge: string;
  chapter: string;
  role: string;
  dockerBuild: string;
  roleDir: string;
  targetDir?: string;
  agents: string[];
  createdAt: string;
  updatedAt: string;
}

/**
 * The top-level structure of chapters.json.
 */
export interface ChaptersJson {
  chapters: ChapterEntry[];
}

const CHAPTERS_JSON = "chapters.json";
const GITIGNORE = ".gitignore";
const GITIGNORE_CONTENT = `# Auto-generated by chapter CLI\n**/logs/\n`;

/**
 * Resolve the CLAWMASONS_HOME directory.
 * Reads from the CLAWMASONS_HOME environment variable; defaults to ~/.clawmasons.
 */
export function getClawmasonsHome(): string {
  const envValue = process.env["CLAWMASONS_HOME"];
  if (envValue) {
    return path.resolve(envValue);
  }
  return path.join(os.homedir(), ".clawmasons");
}

/**
 * Ensure the CLAWMASONS_HOME directory exists with a .gitignore.
 * Creates the directory and .gitignore if they don't exist. Safe to call multiple times.
 */
export function ensureClawmasonsHome(home: string): void {
  fs.mkdirSync(home, { recursive: true });

  const gitignorePath = path.join(home, GITIGNORE);
  if (!fs.existsSync(gitignorePath)) {
    fs.writeFileSync(gitignorePath, GITIGNORE_CONTENT, "utf-8");
  }
}

/**
 * Read and parse chapters.json from the CLAWMASONS_HOME directory.
 * Returns { chapters: [] } when the file doesn't exist.
 * Throws on malformed JSON.
 */
export function readChaptersJson(home: string): ChaptersJson {
  const filePath = path.join(home, CHAPTERS_JSON);
  if (!fs.existsSync(filePath)) {
    return { chapters: [] };
  }

  const content = fs.readFileSync(filePath, "utf-8");
  try {
    const data = JSON.parse(content) as ChaptersJson;
    if (!data.chapters || !Array.isArray(data.chapters)) {
      return { chapters: [] };
    }
    return data;
  } catch (err) {
    throw new Error(
      `Failed to parse ${filePath}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * Write chapters.json to the CLAWMASONS_HOME directory.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
export function writeChaptersJson(home: string, data: ChaptersJson): void {
  const filePath = path.join(home, CHAPTERS_JSON);
  const tmpPath = `${filePath}.tmp`;
  const content = JSON.stringify(data, null, 2) + "\n";
  fs.writeFileSync(tmpPath, content, "utf-8");
  fs.renameSync(tmpPath, filePath);
}

/**
 * Find a role entry in chapters.json by composite key (lodge, chapter, role).
 * Returns undefined if not found.
 */
export function findRoleEntry(
  home: string,
  lodge: string,
  chapter: string,
  role: string,
): ChapterEntry | undefined {
  const data = readChaptersJson(home);
  return data.chapters.find(
    (entry) =>
      entry.lodge === lodge &&
      entry.chapter === chapter &&
      entry.role === role,
  );
}

/**
 * Find a role entry in chapters.json by role name only.
 * Useful when lodge/chapter are not known (e.g., run-agent from a project directory).
 * Returns the first matching entry or undefined.
 */
export function findRoleEntryByRole(
  home: string,
  role: string,
): ChapterEntry | undefined {
  const data = readChaptersJson(home);
  return data.chapters.find((entry) => entry.role === role);
}

/**
 * Insert or update a role entry in chapters.json.
 * Matches by composite key (lodge, chapter, role).
 * If found, updates the existing entry's fields and sets updatedAt.
 * If not found, appends with both createdAt and updatedAt.
 */
// ── Lodge config.json helpers ──────────────────────────────────────────

const CONFIG_JSON = "config.json";

/**
 * A single lodge entry in config.json.
 */
export interface LodgeConfigEntry {
  home: string;
}

/**
 * The top-level structure of config.json: { "<lodge>": { "home": "<path>" } }.
 */
export type ConfigJson = Record<string, LodgeConfigEntry>;

/**
 * Read and parse config.json from the CLAWMASONS_HOME directory.
 * Returns {} when the file doesn't exist.
 * Throws on malformed JSON.
 */
export function readConfigJson(home: string): ConfigJson {
  const filePath = path.join(home, CONFIG_JSON);
  if (!fs.existsSync(filePath)) {
    return {};
  }

  const content = fs.readFileSync(filePath, "utf-8");
  try {
    return JSON.parse(content) as ConfigJson;
  } catch (err) {
    throw new Error(
      `Failed to parse ${filePath}: ${err instanceof Error ? err.message : String(err)}`,
    );
  }
}

/**
 * Write config.json to the CLAWMASONS_HOME directory.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
export function writeConfigJson(home: string, data: ConfigJson): void {
  const filePath = path.join(home, CONFIG_JSON);
  const tmpPath = `${filePath}.tmp`;
  const content = JSON.stringify(data, null, 2) + "\n";
  fs.writeFileSync(tmpPath, content, "utf-8");
  fs.renameSync(tmpPath, filePath);
}

/**
 * Register or update a lodge entry in config.json.
 */
export function upsertLodgeEntry(
  home: string,
  lodge: string,
  lodgeHome: string,
): void {
  const data = readConfigJson(home);
  data[lodge] = { home: lodgeHome };
  writeConfigJson(home, data);
}

/**
 * Get a lodge entry from config.json.
 * Returns undefined if the lodge is not registered.
 */
export function getLodgeEntry(
  home: string,
  lodge: string,
): LodgeConfigEntry | undefined {
  const data = readConfigJson(home);
  return data[lodge];
}

/**
 * Resolve lodge variables from CLI options, env vars, and defaults.
 * Priority: CLI flag > env var > default.
 */
export function resolveLodgeVars(options?: {
  home?: string;
  lodge?: string;
  lodgeHome?: string;
}): { clawmasonsHome: string; lodge: string; lodgeHome: string } {
  const clawmasonsHome = options?.home
    ?? process.env["CLAWMASONS_HOME"]
    ?? path.join(os.homedir(), ".clawmasons");

  const lodge = options?.lodge
    ?? process.env["LODGE"]
    ?? process.env["USER"]
    ?? "anonymous";

  const lodgeHome = options?.lodgeHome
    ?? process.env["LODGE_HOME"]
    ?? path.join(clawmasonsHome, lodge);

  return {
    clawmasonsHome: path.resolve(clawmasonsHome),
    lodge,
    lodgeHome: path.resolve(lodgeHome),
  };
}

// ── chapters.json helpers (existing) ───────────────────────────────────

export function upsertRoleEntry(home: string, entry: ChapterEntry): void {
  const data = readChaptersJson(home);
  const idx = data.chapters.findIndex(
    (existing) =>
      existing.lodge === entry.lodge &&
      existing.chapter === entry.chapter &&
      existing.role === entry.role,
  );

  if (idx >= 0) {
    data.chapters[idx] = {
      ...entry,
      createdAt: data.chapters[idx].createdAt,
      updatedAt: entry.updatedAt,
    };
  } else {
    data.chapters.push(entry);
  }

  writeChaptersJson(home, data);
}
