import type { ResolvedMember, ResolvedRole, ResolvedTask } from "../resolver/types.js";
import { getAppShortName } from "../generator/toolfilter.js";
import type { RuntimeMaterializer, MaterializationResult, ComposeServiceDef } from "./types.js";
import {
  formatPermittedTools,
  collectAllSkills,
  collectAllTasks,
  generateAgentsMd,
  generateSkillReadme,
} from "./common.js";

/**
 * Mapping from LLM provider identifiers to their environment variable names.
 *
 * Used by the materializer to inject the correct API key into the
 * Docker Compose service, and by env template generation to include
 * the key in .env.example.
 *
 * @see PRD §3.3 — Supported Providers
 * @see PRD §7.2 — Provider → Environment Variable Mapping
 */
export const PROVIDER_ENV_VARS: Record<string, string> = {
  "openrouter": "OPENROUTER_API_KEY",
  "anthropic": "ANTHROPIC_API_KEY",
  "openai": "OPENAI_API_KEY",
  "google": "GEMINI_API_KEY",
  "mistral": "MISTRAL_API_KEY",
  "groq": "GROQ_API_KEY",
  "xai": "XAI_API_KEY",
  "azure-openai": "AZURE_OPENAI_API_KEY",
};

/**
 * Generate the command prompt for a pi `registerCommand()` call.
 *
 * Same structure as claude-code's slash commands:
 * - Role context with permitted tools
 * - Skill references
 * - Task prompt
 */
function generateCommandPrompt(
  task: ResolvedTask,
  owningRoles: ResolvedRole[],
): string {
  const lines: string[] = [];

  for (const role of owningRoles) {
    const roleShortName = getAppShortName(role.name);
    lines.push("## Role Context");
    lines.push(`You are operating as role: ${roleShortName}`);
    lines.push("Permitted tools for this role:");
    lines.push(formatPermittedTools(role.permissions));
    lines.push("Do NOT use tools outside this list even if they appear available.");
    lines.push("");
  }

  if (task.skills.length > 0) {
    lines.push("## Required Skills");
    for (const skill of task.skills) {
      const skillShortName = getAppShortName(skill.name);
      lines.push(`See skills/${skillShortName}/ for ${skill.description}.`);
    }
    lines.push("");
  }

  lines.push("## Task");
  if (task.prompt) {
    lines.push(`[contents of ${task.prompt}]`);
  } else {
    lines.push("[no prompt defined]");
  }

  return lines.join("\n");
}

/**
 * Escape a string for use inside a JavaScript template literal.
 * Escapes backticks and ${} expressions.
 */
function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Generate .pi/settings.json content.
 *
 * Declares the active model using pi's model ID format:
 * {provider}/{model} (e.g., "openrouter/anthropic/claude-sonnet-4")
 */
function generatePiSettingsJson(member: ResolvedMember): string {
  if (!member.llm) {
    throw new Error(
      `Pi-coding-agent materializer requires llm configuration on member "${member.name}". ` +
      `Specify llm.provider and llm.model in the member's package.json chapter field.`,
    );
  }

  const modelId = `${member.llm.provider}/${member.llm.model}`;
  return JSON.stringify({ model: modelId }, null, 2);
}

/**
 * Generate .pi/mcp.json content.
 *
 * Creates a single "chapter" MCP server entry pointing at the proxy's
 * unified endpoint:  /sse  (SSE)  or  /mcp  (streamable-http).
 */
function generatePiMcpJson(
  proxyEndpoint: string,
  proxyType: "sse" | "streamable-http",
  proxyToken?: string,
): string {
  const pathSuffix = proxyType === "sse" ? "/sse" : "/mcp";
  const bearerValue = proxyToken
    ? `Bearer ${proxyToken}`
    : "Bearer ${CHAPTER_PROXY_TOKEN}";

  const mcpConfig = {
    mcpServers: {
      chapter: {
        type: proxyType,
        url: `${proxyEndpoint}${pathSuffix}`,
        headers: {
          Authorization: bearerValue,
        },
      },
    },
  };

  return JSON.stringify(mcpConfig, null, 2);
}

/**
 * Generate .pi/extensions/chapter-mcp/package.json content.
 */
function generateExtensionPackageJson(): string {
  return JSON.stringify(
    {
      name: "chapter-mcp",
      version: "1.0.0",
      type: "module",
      main: "index.ts",
    },
    null,
    2,
  );
}

/**
 * Generate .pi/extensions/chapter-mcp/index.ts content.
 *
 * Creates a pi extension that registers each chapter task as a pi command.
 * MCP server configuration lives in .pi/mcp.json (not in extension code).
 */
function generateExtensionIndexTs(
  member: ResolvedMember,
): string {
  const lines: string[] = [];
  lines.push("// Generated by the pi-coding-agent materializer");
  lines.push("export default (pi) => {");

  // Register each task as a pi command
  const allTasks = collectAllTasks(member.roles);
  for (const [task, owningRoles] of allTasks) {
    const taskShortName = getAppShortName(task.name);
    const description = `${task.name}@${task.version}`;
    const prompt = generateCommandPrompt(task, owningRoles);

    lines.push("");
    lines.push("  pi.registerCommand({");
    lines.push(`    name: "${taskShortName}",`);
    lines.push(`    description: "${escapeTemplateLiteral(description)}",`);
    lines.push(`    prompt: \`${escapeTemplateLiteral(prompt)}\`,`);
    lines.push("  });");
  }

  lines.push("};");

  return lines.join("\n");
}

/**
 * Pi Coding Agent runtime materializer.
 *
 * Generates a workspace directory for pi-coding-agent:
 * - AGENTS.md — agent identity and role documentation
 * - .pi/settings.json — model configuration
 * - .pi/extensions/chapter-mcp/ — MCP proxy bridge extension
 * - skills/{name}/README.md — skill artifact manifests
 */
export const piCodingAgentMaterializer: RuntimeMaterializer = {
  name: "pi-coding-agent",

  materializeWorkspace(
    member: ResolvedMember,
    proxyEndpoint: string,
    proxyToken?: string,
  ): MaterializationResult {
    const result: MaterializationResult = new Map();

    // AGENTS.md — agent identity and role docs (shared with claude-code)
    result.set("AGENTS.md", generateAgentsMd(member));

    // .pi/settings.json — model configuration
    result.set(".pi/settings.json", generatePiSettingsJson(member));

    // .pi/mcp.json — MCP server config
    const proxyType = member.proxy?.type ?? "sse";
    result.set(
      ".pi/mcp.json",
      generatePiMcpJson(proxyEndpoint, proxyType, proxyToken),
    );

    // .pi/extensions/chapter-mcp/package.json
    result.set(
      ".pi/extensions/chapter-mcp/package.json",
      generateExtensionPackageJson(),
    );

    // .pi/extensions/chapter-mcp/index.ts — task commands
    result.set(
      ".pi/extensions/chapter-mcp/index.ts",
      generateExtensionIndexTs(member),
    );

    // skills/{skill-short-name}/README.md
    const allSkills = collectAllSkills(member.roles);
    for (const [, skill] of allSkills) {
      const skillShortName = getAppShortName(skill.name);
      result.set(
        `skills/${skillShortName}/README.md`,
        generateSkillReadme(skill),
      );
    }

    return result;
  },

  generateDockerfile(): string {
    return [
      "FROM node:22-slim",
      "",
      "RUN npm install -g @mariozechner/pi-coding-agent",
      "",
      "USER node",
      "WORKDIR /home/node/workspace",
      "COPY --chown=node:node workspace/ /home/node/workspace/",
      "",
      'CMD ["pi", "--no-session", "--mode", "print"]',
    ].join("\n");
  },

  generateComposeService(member: ResolvedMember): ComposeServiceDef {
    const roleNames = member.roles
      .map((r) => getAppShortName(r.name))
      .join(",");

    const port = member.proxy?.port ?? 9090;
    const environment: string[] = [
      `CHAPTER_ROLES=${roleNames}`,
    ];

    // Add LLM provider API key env var (dynamic based on llm.provider)
    if (member.llm) {
      const envVar = PROVIDER_ENV_VARS[member.llm.provider];
      if (envVar) {
        environment.push(`${envVar}=\${${envVar}}`);
      }
    }

    // Add proxy connection env vars
    environment.push("CHAPTER_PROXY_TOKEN=${CHAPTER_PROXY_TOKEN}");
    environment.push(`CHAPTER_PROXY_ENDPOINT=http://mcp-proxy:${port}`);

    return {
      build: "./pi-coding-agent",
      restart: "no",
      volumes: [
        "./pi-coding-agent/workspace:/home/node/workspace",
      ],
      working_dir: "/home/node/workspace",
      environment,
      depends_on: ["mcp-proxy"],
      stdin_open: true,
      tty: true,
      init: true,
      networks: ["chapter-net"],
    };
  },
};
