import type { Command } from "commander";
import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import { spawn } from "node:child_process";
import type { RunConfig } from "./run-init.js";
import { checkDockerCompose } from "./docker-utils.js";
import { PROVIDER_ENV_VARS } from "../../materializer/common.js";

/**
 * Generate a short unique session ID (8 hex characters).
 */
export function generateSessionId(): string {
  return crypto.randomBytes(4).toString("hex");
}

/**
 * Read and validate the run-init `.clawmasons/chapter.json` config
 * from the given project directory.
 */
export function readRunConfig(projectDir: string): RunConfig {
  const configPath = path.join(projectDir, ".clawmasons", "chapter.json");

  if (!fs.existsSync(configPath)) {
    throw new Error(
      `No .clawmasons/chapter.json found. Run "chapter run-init" first to initialize the project.`,
    );
  }

  let raw: unknown;
  try {
    raw = JSON.parse(fs.readFileSync(configPath, "utf-8"));
  } catch {
    throw new Error(`.clawmasons/chapter.json is not valid JSON.`);
  }

  if (
    typeof raw !== "object" ||
    raw === null ||
    !("chapter" in raw) ||
    typeof (raw as RunConfig).chapter !== "string" ||
    !("docker-build" in raw) ||
    typeof (raw as RunConfig)["docker-build"] !== "string"
  ) {
    throw new Error(
      `.clawmasons/chapter.json must contain "chapter" and "docker-build" fields. Run "chapter run-init" to regenerate.`,
    );
  }

  return raw as RunConfig;
}

/**
 * Validate that the docker-build path has the expected Dockerfiles
 * for the given agent and role.
 */
export function validateDockerfiles(
  dockerBuildPath: string,
  agent: string,
  role: string,
): { proxyDockerfile: string; agentDockerfile: string } {
  const proxyDockerfile = path.join(dockerBuildPath, "proxy", role, "Dockerfile");
  const agentDockerfile = path.join(dockerBuildPath, "agent", agent, role, "Dockerfile");

  if (!fs.existsSync(proxyDockerfile)) {
    throw new Error(
      `Proxy Dockerfile not found: ${proxyDockerfile}\nRun "chapter docker-init" in the chapter project to generate Dockerfiles.`,
    );
  }

  if (!fs.existsSync(agentDockerfile)) {
    throw new Error(
      `Agent Dockerfile not found: ${agentDockerfile}\nRun "chapter docker-init" in the chapter project to generate Dockerfiles.`,
    );
  }

  return { proxyDockerfile, agentDockerfile };
}

/**
 * Generate a docker-compose.yml for a run-agent session.
 *
 * The compose file defines two services:
 * - proxy: built from the proxy Dockerfile, runs detached
 * - agent: built from the agent Dockerfile, runs interactively with stdin
 *
 * The project directory is bind-mounted into both containers at /workspace.
 */
export function generateComposeYml(opts: {
  dockerBuildPath: string;
  projectDir: string;
  agent: string;
  role: string;
  logsDir: string;
  proxyToken: string;
}): string {
  const { dockerBuildPath, projectDir, agent, role, logsDir, proxyToken } = opts;

  const proxyContext = path.join(dockerBuildPath);
  const proxyDockerfile = path.join("proxy", role, "Dockerfile");
  const agentContext = path.join(dockerBuildPath);
  const agentDockerfile = path.join("agent", agent, role, "Dockerfile");

  const proxyServiceName = `proxy-${role}`;
  const agentServiceName = `agent-${agent}-${role}`;

  // Pass all known LLM provider API keys from host to agent container.
  // Only keys that are set on the host will have values.
  const envLines = Object.values(PROVIDER_ENV_VARS)
    .map((envVar) => `      - ${envVar}=\${${envVar}:-}`)
    .join("\n");

  // Use YAML template literal for clarity
  return `# Generated by chapter run-agent
services:
  ${proxyServiceName}:
    build:
      context: "${proxyContext}"
      dockerfile: "${proxyDockerfile}"
    volumes:
      - "${projectDir}:/workspace"
      - "${logsDir}:/logs"
    environment:
      - CHAPTER_PROXY_TOKEN=${proxyToken}
    restart: "no"

  ${agentServiceName}:
    build:
      context: "${agentContext}"
      dockerfile: "${agentDockerfile}"
    volumes:
      - "${projectDir}:/workspace"
    depends_on:
      - ${proxyServiceName}
    environment:
      - CHAPTER_PROXY_TOKEN=${proxyToken}
${envLines}
    stdin_open: true
    tty: true
    init: true
    restart: "no"
`;
}

/**
 * Execute a docker compose command with the given compose file.
 * Returns a promise that resolves with the exit code.
 */
export function execComposeCommand(
  composeFile: string,
  args: string[],
  opts?: { interactive?: boolean },
): Promise<number> {
  const baseArgs = ["compose", "-f", composeFile, ...args];
  const stdio = opts?.interactive ? "inherit" as const : "ignore" as const;

  return new Promise((resolve) => {
    const child = spawn("docker", baseArgs, { stdio });
    child.on("close", (code) => resolve(code ?? 0));
    child.on("error", () => resolve(1));
  });
}

/**
 * Dependencies for run-agent, injectable for testing.
 */
export interface RunAgentDeps {
  /** Override the compose command executor (for testing). */
  execComposeFn?: (
    composeFile: string,
    args: string[],
    opts?: { interactive?: boolean },
  ) => Promise<number>;
  /** Override session ID generation (for testing). */
  generateSessionIdFn?: () => string;
  /** Override docker compose check (for testing). */
  checkDockerComposeFn?: () => void;
}

export function registerRunAgentCommand(program: Command): void {
  program
    .command("run-agent")
    .description("Run a chapter agent interactively against this project")
    .argument("<agent>", "Agent name (e.g., note-taker)")
    .argument("<role>", "Role name (e.g., writer)")
    .action(async (agent: string, role: string) => {
      await runAgent(process.cwd(), agent, role);
    });
}

export async function runAgent(
  projectDir: string,
  agent: string,
  role: string,
  deps?: RunAgentDeps,
): Promise<void> {
  const execCompose = deps?.execComposeFn ?? execComposeCommand;
  const genSessionId = deps?.generateSessionIdFn ?? generateSessionId;
  const checkDocker = deps?.checkDockerComposeFn ?? checkDockerCompose;

  try {
    // 1. Pre-flight: check docker compose is available
    checkDocker();

    // 2. Read project config
    const config = readRunConfig(projectDir);
    const dockerBuildPath = config["docker-build"];

    console.log(`\n  Chapter: ${config.chapter}`);
    console.log(`  Agent: ${agent}`);
    console.log(`  Role: ${role}`);

    // 3. Validate Dockerfiles exist
    validateDockerfiles(dockerBuildPath, agent, role);

    // 4. Generate session ID and create session directory
    const sessionId = genSessionId();
    const sessionDir = path.join(projectDir, ".clawmasons", "sessions", sessionId, "docker");
    fs.mkdirSync(sessionDir, { recursive: true });

    const logsDir = path.join(projectDir, ".clawmasons", "logs");
    fs.mkdirSync(logsDir, { recursive: true });

    console.log(`  Session: ${sessionId}`);

    // 5. Generate docker-compose.yml
    const proxyToken = crypto.randomBytes(32).toString("hex");
    const composeContent = generateComposeYml({
      dockerBuildPath,
      projectDir,
      agent,
      role,
      logsDir,
      proxyToken,
    });

    const composeFile = path.join(sessionDir, "docker-compose.yml");
    fs.writeFileSync(composeFile, composeContent);
    console.log(`  Compose: .clawmasons/sessions/${sessionId}/docker/docker-compose.yml`);

    // 6. Start proxy detached
    const proxyServiceName = `proxy-${role}`;
    console.log(`\n  Starting proxy (${proxyServiceName})...`);

    const proxyCode = await execCompose(
      composeFile,
      ["up", "-d", proxyServiceName],
    );
    if (proxyCode !== 0) {
      throw new Error(`Failed to start proxy (exit code ${proxyCode}).`);
    }
    console.log(`  Proxy started in background.`);

    // 7. Start agent interactively
    const agentServiceName = `agent-${agent}-${role}`;
    console.log(`  Starting agent (${agentServiceName})...\n`);

    const agentCode = await execCompose(
      composeFile,
      ["up", agentServiceName],
      { interactive: true },
    );

    // 8. Tear down proxy on agent exit
    console.log(`\n  Agent exited (code ${agentCode}). Tearing down proxy...`);

    await execCompose(composeFile, ["down"]);

    console.log(`  Proxy stopped.`);
    console.log(`  Session retained at: .clawmasons/sessions/${sessionId}/`);
    console.log(`\n  run-agent complete\n`);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error(`\n  run-agent failed: ${message}\n`);
    process.exit(1);
  }
}
