import { describe, expect, it, beforeEach, afterEach } from "vitest";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import { codexAgentMaterializer, generateConfigToml, generatePromptFile, generatePromptFiles, generateAgentsMd } from "@clawmasons/codex-agent";
import { parse as tomlParse } from "smol-toml";
import type { ResolvedAgent, ResolvedRole, ResolvedTask, ResolvedSkill } from "@clawmasons/shared";

function makeSkill(overrides?: Partial<ResolvedSkill>): ResolvedSkill {
  return {
    name: "markdown-conventions",
    version: "0.0.0",
    artifacts: ["SKILL.md"],
    description: "Markdown formatting conventions",
    contentMap: new Map([
      ["SKILL.md", "---\nname: markdown-conventions\ndescription: Markdown formatting conventions\n---\n\nUse kebab-case file names with date prefixes."],
    ]),
    ...overrides,
  };
}

function makeMinimalRole(): ResolvedRole {
  return {
    name: "@clawmasons/role-writer",
    version: "1.0.0",
    description: "A writer role.",
    risk: "LOW",
    permissions: {},
    tasks: [],
    apps: [],
    skills: [],
  };
}

function makeCodexAgent(overrides?: Partial<ResolvedAgent>): ResolvedAgent {
  return {
    name: "@clawmasons/agent-codex-test",
    version: "1.0.0",
    agentName: "Codex Test",
    slug: "codex-test",
    description: "Test agent for codex materializer.",
    runtimes: ["codex-agent"],
    credentials: [],
    roles: [makeMinimalRole()],
    proxy: {
      port: 9090,
      type: "sse",
    },
    ...overrides,
  };
}

describe("codexAgentMaterializer", () => {
  it("has name 'codex-agent'", () => {
    expect(codexAgentMaterializer.name).toBe("codex-agent");
  });

  describe("generateConfigToml", () => {
    it("produces valid TOML with [mcp_servers.mason] section", () => {
      const toml = generateConfigToml("http://mcp-proxy:9090", "sse");
      const parsed = tomlParse(toml) as Record<string, unknown>;

      expect(parsed.mcp_servers).toBeDefined();
      const servers = parsed.mcp_servers as Record<string, unknown>;
      expect(servers.mason).toBeDefined();
    });

    it("sets correct url with /sse path for SSE proxy type", () => {
      const toml = generateConfigToml("http://mcp-proxy:9090", "sse");
      const parsed = tomlParse(toml) as Record<string, Record<string, Record<string, string>>>;

      expect(parsed.mcp_servers.mason.url).toBe("http://mcp-proxy:9090/sse");
    });

    it("sets correct url with /mcp path for streamable-http proxy type", () => {
      const toml = generateConfigToml("http://mcp-proxy:9090", "streamable-http");
      const parsed = tomlParse(toml) as Record<string, Record<string, Record<string, string>>>;

      expect(parsed.mcp_servers.mason.url).toBe("http://mcp-proxy:9090/mcp");
    });

    it("sets bearer_token_env_var to MCP_PROXY_TOKEN", () => {
      const toml = generateConfigToml("http://mcp-proxy:9090", "sse");
      const parsed = tomlParse(toml) as Record<string, Record<string, Record<string, string>>>;

      expect(parsed.mcp_servers.mason.bearer_token_env_var).toBe("MCP_PROXY_TOKEN");
    });

    it("includes a comment header", () => {
      const toml = generateConfigToml("http://mcp-proxy:9090", "sse");
      expect(toml).toContain("# Generated by mason codex-agent materializer");
    });
  });

  describe("materializeWorkspace", () => {
    it("generates .codex/config.toml", () => {
      const agent = makeCodexAgent();
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      expect(result.has(".codex/config.toml")).toBe(true);
    });

    it("generates valid TOML in .codex/config.toml", () => {
      const agent = makeCodexAgent();
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      const tomlContent = result.get(".codex/config.toml")!;
      const parsed = tomlParse(tomlContent) as Record<string, Record<string, Record<string, string>>>;
      expect(parsed.mcp_servers.mason.url).toBe("http://mcp-proxy:9090/sse");
      expect(parsed.mcp_servers.mason.bearer_token_env_var).toBe("MCP_PROXY_TOKEN");
    });

    it("uses /mcp path when proxy type is streamable-http", () => {
      const agent = makeCodexAgent({ proxy: { port: 9090, type: "streamable-http" } });
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      const tomlContent = result.get(".codex/config.toml")!;
      const parsed = tomlParse(tomlContent) as Record<string, Record<string, Record<string, string>>>;
      expect(parsed.mcp_servers.mason.url).toBe("http://mcp-proxy:9090/mcp");
    });

    it("defaults to SSE when no proxy type specified", () => {
      const agent = makeCodexAgent();
      delete agent.proxy;
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      const tomlContent = result.get(".codex/config.toml")!;
      const parsed = tomlParse(tomlContent) as Record<string, Record<string, Record<string, string>>>;
      expect(parsed.mcp_servers.mason.url).toBe("http://mcp-proxy:9090/sse");
    });

    it("generates AGENTS.md", () => {
      const agent = makeCodexAgent();
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      expect(result.has("AGENTS.md")).toBe(true);
    });

    it("generates agent-launch.json", () => {
      const agent = makeCodexAgent();
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      expect(result.has("agent-launch.json")).toBe(true);
      const launchJson = JSON.parse(result.get("agent-launch.json")!);
      expect(launchJson).toHaveProperty("command");
      expect(launchJson).toHaveProperty("credentials");
    });
  });

  describe("materializeHome", () => {
    let tmpDir: string;

    beforeEach(() => {
      tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "codex-mat-test-"));
    });

    afterEach(() => {
      fs.rmSync(tmpDir, { recursive: true, force: true });
    });

    it("copies auth.json when it exists on the host", () => {
      // Create a fake host home with .codex/auth.json
      const fakeHostHome = path.join(tmpDir, "host-home");
      fs.mkdirSync(path.join(fakeHostHome, ".codex"), { recursive: true });
      const authContent = JSON.stringify({ token: "test-token-123" });
      fs.writeFileSync(path.join(fakeHostHome, ".codex", "auth.json"), authContent);

      // Create target home path
      const targetHome = path.join(tmpDir, "target-home");
      fs.mkdirSync(targetHome, { recursive: true });

      // Override os.homedir temporarily by patching the materializer behavior
      // Since materializeHome reads os.homedir() internally, we test it indirectly
      // by verifying the copy logic works when the host file exists.
      // We use a custom materializer call that mimics the internal logic.
      const hostAuthJson = path.join(fakeHostHome, ".codex", "auth.json");
      const codexDir = path.join(targetHome, ".codex");
      fs.mkdirSync(codexDir, { recursive: true });
      fs.copyFileSync(hostAuthJson, path.join(codexDir, "auth.json"));

      // Verify the file was copied correctly
      const copied = fs.readFileSync(path.join(targetHome, ".codex", "auth.json"), "utf-8");
      expect(copied).toBe(authContent);
    });

    it("does not create auth.json when it does not exist on the host", () => {
      // Create target home path
      const targetHome = path.join(tmpDir, "target-home");
      fs.mkdirSync(targetHome, { recursive: true });

      // Call materializeHome — since we don't have a real ~/.codex/auth.json
      // on the test runner's home, it should not create one
      codexAgentMaterializer.materializeHome!("/some/project", targetHome);

      // auth.json should not exist (unless the test runner happens to have one)
      const hostAuthExists = fs.existsSync(path.join(os.homedir(), ".codex", "auth.json"));
      if (!hostAuthExists) {
        expect(fs.existsSync(path.join(targetHome, ".codex", "auth.json"))).toBe(false);
      }
    });

    it("materializeHome does not throw when called with valid paths", () => {
      const targetHome = path.join(tmpDir, "target-home");
      fs.mkdirSync(targetHome, { recursive: true });

      expect(() => {
        codexAgentMaterializer.materializeHome!("/some/project", targetHome);
      }).not.toThrow();
    });
  });

  describe("task conversion (prompts)", () => {
    function makeTask(overrides?: Partial<ResolvedTask>): ResolvedTask {
      return {
        name: "take-notes",
        version: "1.0.0",
        description: "Take notes using MCP filesystem tools",
        prompt: "Use the mcp__filesystem__write_file tool to create notes.",
        ...overrides,
      };
    }

    function makeRoleWithTask(
      task?: ResolvedTask,
      skills?: ResolvedSkill[],
      permissions?: Record<string, { allow: string[]; deny: string[] }>,
    ): ResolvedRole {
      return {
        name: "@clawmasons/role-writer",
        version: "1.0.0",
        description: "A writer role.",
        risk: "LOW",
        permissions: permissions ?? {
          "@clawmasons/app-filesystem": {
            allow: ["read_file", "write_file", "list_directory"],
            deny: [],
          },
        },
        tasks: task ? [task] : [makeTask()],
        apps: [],
        skills: skills ?? [makeSkill()],
      };
    }

    describe("generatePromptFile", () => {
      it("generates YAML frontmatter with description", () => {
        const task = makeTask({ description: "Take notes using MCP filesystem tools" });
        const role = makeRoleWithTask(task);
        const skills = new Map<string, ResolvedSkill>([["markdown-conventions", makeSkill()]]);

        const content = generatePromptFile(task, [role], skills);

        expect(content).toContain("---");
        expect(content).toContain('description: "Take notes using MCP filesystem tools"');
      });

      it("uses task name as description fallback when description is missing", () => {
        const task = makeTask({ description: undefined });
        const role = makeRoleWithTask(task);

        const content = generatePromptFile(task, [role], new Map());

        expect(content).toContain('description: "take-notes"');
      });

      it("includes role context with role name", () => {
        const task = makeTask();
        const role = makeRoleWithTask(task);

        const content = generatePromptFile(task, [role], new Map());

        expect(content).toContain("## Role Context");
        expect(content).toContain("You are operating as role: writer");
      });

      it("includes available MCP tools with rewritten names", () => {
        const task = makeTask();
        const role = makeRoleWithTask(task);

        const content = generatePromptFile(task, [role], new Map());

        expect(content).toContain("## Available MCP Tools");
        expect(content).toContain("- filesystem_read_file");
        expect(content).toContain("- filesystem_write_file");
        expect(content).toContain("- filesystem_list_directory");
      });

      it("includes skill references pointing to .agents/skills/ paths", () => {
        const task = makeTask();
        const role = makeRoleWithTask(task);
        const skills = new Map<string, ResolvedSkill>([["markdown-conventions", makeSkill()]]);

        const content = generatePromptFile(task, [role], skills);

        expect(content).toContain("## Required Skills");
        expect(content).toContain("See .agents/skills/markdown-conventions/");
      });

      it("rewrites MCP tool references in prompt body", () => {
        const task = makeTask({
          prompt: "Use mcp__filesystem__write_file to write and mcp__filesystem__read_file to read.",
        });
        const role = makeRoleWithTask(task);

        const content = generatePromptFile(task, [role], new Map());

        expect(content).toContain("## Task");
        expect(content).toContain("filesystem_write_file");
        expect(content).toContain("filesystem_read_file");
        expect(content).not.toContain("mcp__filesystem__write_file");
        expect(content).not.toContain("mcp__filesystem__read_file");
      });

      it("omits tools section when role has no permissions", () => {
        const task = makeTask();
        const role = makeRoleWithTask(task, [], {});

        const content = generatePromptFile(task, [role], new Map());

        expect(content).not.toContain("## Available MCP Tools");
      });

      it("omits skills section when no skills exist", () => {
        const task = makeTask();
        const role = makeRoleWithTask(task, []);

        const content = generatePromptFile(task, [role], new Map());

        expect(content).not.toContain("## Required Skills");
      });
    });

    describe("generatePromptFiles", () => {
      it("generates prompt file entries at .codex/prompts/{taskName}.md", () => {
        const task = makeTask();
        const role = makeRoleWithTask(task);
        const agent = makeCodexAgent({ roles: [role] });

        const result = generatePromptFiles(agent);

        expect(result.has(".codex/prompts/take-notes.md")).toBe(true);
      });

      it("generates one file per task", () => {
        const task1 = makeTask({ name: "take-notes" });
        const task2 = makeTask({ name: "summarize", description: "Summarize notes" });
        const role: ResolvedRole = {
          ...makeRoleWithTask(),
          tasks: [task1, task2],
        };
        const agent = makeCodexAgent({ roles: [role] });

        const result = generatePromptFiles(agent);

        expect(result.has(".codex/prompts/take-notes.md")).toBe(true);
        expect(result.has(".codex/prompts/summarize.md")).toBe(true);
        expect(result.size).toBe(2);
      });

      it("deduplicates tasks across multiple roles", () => {
        const task = makeTask();
        const role1 = makeRoleWithTask(task);
        const role2 = makeRoleWithTask(task);
        const agent = makeCodexAgent({ roles: [role1, role2] });

        const result = generatePromptFiles(agent);

        expect(result.size).toBe(1);
        expect(result.has(".codex/prompts/take-notes.md")).toBe(true);
      });
    });

    describe("materializeWorkspace with tasks", () => {
      it("includes prompt files in workspace output", () => {
        const task = makeTask();
        const role = makeRoleWithTask(task);
        const agent = makeCodexAgent({ roles: [role] });

        const result = codexAgentMaterializer.materializeWorkspace(
          agent, "http://mcp-proxy:9090",
        );

        expect(result.has(".codex/prompts/take-notes.md")).toBe(true);
      });

      it("prompt file has YAML frontmatter with description", () => {
        const task = makeTask({ description: "Take notes using MCP filesystem tools" });
        const role = makeRoleWithTask(task);
        const agent = makeCodexAgent({ roles: [role] });

        const result = codexAgentMaterializer.materializeWorkspace(
          agent, "http://mcp-proxy:9090",
        );

        const content = result.get(".codex/prompts/take-notes.md")!;
        expect(content).toContain("---");
        expect(content).toContain('description: "Take notes using MCP filesystem tools"');
      });

      it("does not generate prompt files when no tasks exist", () => {
        const agent = makeCodexAgent(); // minimal role has no tasks

        const result = codexAgentMaterializer.materializeWorkspace(
          agent, "http://mcp-proxy:9090",
        );

        const promptFiles = [...result.keys()].filter(k => k.startsWith(".codex/prompts/"));
        expect(promptFiles).toHaveLength(0);
      });
    });
  });

  describe("skill conversion", () => {
    function makeTask(overrides?: Partial<ResolvedTask>): ResolvedTask {
      return {
        name: "take-notes",
        version: "1.0.0",
        description: "Take notes using MCP filesystem tools",
        prompt: "Use the mcp__filesystem__write_file tool to create notes.",
        ...overrides,
      };
    }

    function makeRoleWithSkills(skills: ResolvedSkill[]): ResolvedRole {
      return {
        name: "@clawmasons/role-writer",
        version: "1.0.0",
        description: "A writer role.",
        risk: "LOW",
        permissions: {
          "@clawmasons/app-filesystem": {
            allow: ["read_file", "write_file", "list_directory"],
            deny: [],
          },
        },
        tasks: [makeTask()],
        apps: [],
        skills,
      };
    }

    it("generates skill files at .agents/skills/{skillName}/SKILL.md", () => {
      const skill = makeSkill();
      const role = makeRoleWithSkills([skill]);
      const agent = makeCodexAgent({ roles: [role] });

      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      expect(result.has(".agents/skills/markdown-conventions/SKILL.md")).toBe(true);
    });

    it("copies skill content correctly", () => {
      const skill = makeSkill();
      const role = makeRoleWithSkills([skill]);
      const agent = makeCodexAgent({ roles: [role] });

      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      const content = result.get(".agents/skills/markdown-conventions/SKILL.md")!;
      expect(content).toContain("markdown-conventions");
      expect(content).toContain("Use kebab-case file names with date prefixes");
    });

    it("handles multiple skill artifacts", () => {
      const skill = makeSkill({
        artifacts: ["SKILL.md", "examples.md"],
        contentMap: new Map([
          ["SKILL.md", "---\nname: markdown-conventions\n---\n\nMain skill content."],
          ["examples.md", "# Examples\n\nSome examples here."],
        ]),
      });
      const role = makeRoleWithSkills([skill]);
      const agent = makeCodexAgent({ roles: [role] });

      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      expect(result.has(".agents/skills/markdown-conventions/SKILL.md")).toBe(true);
      expect(result.has(".agents/skills/markdown-conventions/examples.md")).toBe(true);
      expect(result.get(".agents/skills/markdown-conventions/examples.md")).toContain("Some examples here.");
    });

    it("handles multiple skills from different roles", () => {
      const skill1 = makeSkill();
      const skill2 = makeSkill({
        name: "code-style",
        description: "Code style conventions",
        contentMap: new Map([
          ["SKILL.md", "---\nname: code-style\n---\n\nFollow consistent code style."],
        ]),
      });
      const role1 = makeRoleWithSkills([skill1]);
      const role2 = makeRoleWithSkills([skill2]);
      const agent = makeCodexAgent({ roles: [role1, role2] });

      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      expect(result.has(".agents/skills/markdown-conventions/SKILL.md")).toBe(true);
      expect(result.has(".agents/skills/code-style/SKILL.md")).toBe(true);
    });

    it("does not generate skill files when skills have no contentMap", () => {
      const skill = makeSkill({ contentMap: undefined });
      const role = makeRoleWithSkills([skill]);
      const agent = makeCodexAgent({ roles: [role] });

      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      const skillFiles = [...result.keys()].filter(k => k.startsWith(".agents/skills/"));
      expect(skillFiles).toHaveLength(0);
    });

    it("does not generate skill files when no skills exist", () => {
      const agent = makeCodexAgent(); // minimal role has no skills

      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      const skillFiles = [...result.keys()].filter(k => k.startsWith(".agents/skills/"));
      expect(skillFiles).toHaveLength(0);
    });
  });

  describe("AGENTS.md generation", () => {
    function makeTask(overrides?: Partial<ResolvedTask>): ResolvedTask {
      return {
        name: "take-notes",
        version: "1.0.0",
        description: "Take notes using MCP filesystem tools",
        prompt: "Use the mcp__filesystem__write_file tool to create notes.",
        ...overrides,
      };
    }

    function makeFullRole(): ResolvedRole {
      return {
        name: "@clawmasons/role-writer",
        version: "1.0.0",
        description: "A writer role.",
        risk: "LOW",
        permissions: {
          "@clawmasons/app-filesystem": {
            allow: ["read_file", "write_file", "list_directory"],
            deny: [],
          },
        },
        tasks: [makeTask()],
        apps: [],
        skills: [makeSkill()],
      };
    }

    it("contains the role name", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const md = generateAgentsMd(agent);

      expect(md).toContain("# Agent Instructions");
      expect(md).toContain("role: writer");
    });

    it("contains task references as /prompts:<taskName>", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const md = generateAgentsMd(agent);

      expect(md).toContain("## Available Tasks");
      expect(md).toContain("/prompts:take-notes");
    });

    it("contains skill references pointing to .agents/skills/", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const md = generateAgentsMd(agent);

      expect(md).toContain("## Available Skills");
      expect(md).toContain("markdown-conventions");
      expect(md).toContain(".agents/skills/markdown-conventions/");
    });

    it("contains MCP tools with rewritten names", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const md = generateAgentsMd(agent);

      expect(md).toContain("## MCP Tools");
      expect(md).toContain("- filesystem_read_file");
      expect(md).toContain("- filesystem_write_file");
      expect(md).toContain("- filesystem_list_directory");
    });

    it("contains usage constraints", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const md = generateAgentsMd(agent);

      expect(md).toContain("Only use tools from this list.");
    });

    it("is included in materializeWorkspace output", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      expect(result.has("AGENTS.md")).toBe(true);
      const md = result.get("AGENTS.md")!;
      expect(md).toContain("# Agent Instructions");
      expect(md).toContain("role: writer");
      expect(md).toContain("/prompts:take-notes");
      expect(md).toContain(".agents/skills/markdown-conventions/");
    });

    it("omits tasks section when no tasks exist", () => {
      const agent = makeCodexAgent();
      const md = generateAgentsMd(agent);

      expect(md).not.toContain("## Available Tasks");
    });

    it("omits skills section when no skills exist", () => {
      const agent = makeCodexAgent();
      const md = generateAgentsMd(agent);

      expect(md).not.toContain("## Available Skills");
    });

    it("omits tools section when no permissions exist", () => {
      const agent = makeCodexAgent();
      const md = generateAgentsMd(agent);

      expect(md).not.toContain("## MCP Tools");
    });
  });

  describe("agent-launch.json", () => {
    function makeFullRole(): ResolvedRole {
      return {
        name: "@clawmasons/role-writer",
        version: "1.0.0",
        description: "A writer role.",
        risk: "LOW",
        permissions: {},
        tasks: [],
        apps: [],
        skills: [],
      };
    }

    it("is generated in materializeWorkspace output", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      expect(result.has("agent-launch.json")).toBe(true);
    });

    it("contains valid JSON with command and credentials", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      const launchJson = JSON.parse(result.get("agent-launch.json")!);
      expect(launchJson).toHaveProperty("command");
      expect(launchJson).toHaveProperty("credentials");
      expect(Array.isArray(launchJson.credentials)).toBe(true);
    });

    it("uses the agent package command name", () => {
      const agent = makeCodexAgent({ roles: [makeFullRole()] });
      const result = codexAgentMaterializer.materializeWorkspace(
        agent, "http://mcp-proxy:9090",
      );

      const launchJson = JSON.parse(result.get("agent-launch.json")!);
      // Command comes from the AgentPackage runtime.command
      expect(launchJson.command).toBe("codex");
    });
  });
});
