import type { ResolvedAgent, ResolvedRole } from "@clawmasons/shared";
import { getAppShortName } from "@clawmasons/shared";

export interface AgentDockerfileOptions {
  /** Whether a materialized home directory exists for this agent. */
  hasHome?: boolean;
}

/**
 * Generate a Dockerfile for an agent container scoped to a single role.
 *
 * All agent containers use `agent-entry` as their unified entrypoint.
 * The agent-entry binary reads `agent-launch.json` (generated by the
 * materializer) to determine what credentials to fetch and which
 * runtime command to execute.
 *
 * The agent image is configured with the materialized workspace files
 * (generated by the runtime materializer) and expects a project directory
 * to be mounted at `/home/mason/workspace/project/`.
 *
 * All agent images run as `USER mason`.
 *
 * The generated Dockerfile uses `docker/` as its build context
 * (the Dockerfile lives at `docker/agent/<agent-name>/<role-name>/Dockerfile`).
 *
 * LLM provider API keys are NOT baked into the image — they are passed
 * at runtime via docker-compose environment variables.
 *
 * @param agent  The fully resolved agent.
 * @param role   The specific role for this agent image.
 * @param options Optional configuration (e.g., hasHome for home directory materialization).
 */
export function generateAgentDockerfile(
  agent: ResolvedAgent,
  role: ResolvedRole,
  options?: AgentDockerfileOptions,
): string {
  const agentShortName = getAppShortName(agent.name);
  const roleShortName = getAppShortName(role.name);
  const hasHome = options?.hasHome ?? false;

  // Determine the runtime — first runtime is the primary one
  const primaryRuntime = agent.runtimes[0] ?? "claude-code";

  // Build runtime-specific install step (entrypoint is always agent-entry)
  const runtimeInstall = getRuntimeInstall(primaryRuntime);

  // Workspace files are COPY'd from a pre-generated directory
  // The workspace dir is created by docker-init at:
  //   docker/<role-short-name>/<agent-type>/workspace/
  // Build context is docker/ (the parent containing node_modules)
  const workspaceCopyLine = `COPY ${roleShortName}/${primaryRuntime}/workspace/ /home/mason/workspace/`;

  // Use role's baseImage if specified, otherwise default to node:22-slim
  const baseImage = role.baseImage ?? "node:22-slim";

  // Build apt-get install step if role declares aptPackages
  const aptInstallStep =
    role.aptPackages && role.aptPackages.length > 0
      ? `\n# Install role-declared apt packages\nRUN apt-get update && apt-get install -y --no-install-recommends ${role.aptPackages.join(" ")} && rm -rf /var/lib/apt/lists/*\n`
      : "";

  // Home directory COPY and backup (when materialized home exists)
  const homeCopyLines = hasHome
    ? `
# Copy materialized host config into home directory
COPY ${roleShortName}/${primaryRuntime}/home/ /home/mason/
RUN chown -R mason:mason /home/mason
`
    : "";

  // Backup home dir before mount overlay (preserves OS files like .bashrc)
  const homeBackupLine = hasHome
    ? `\n# Backup home before mount overlay\nRUN cp -a /home/mason /home/mason-from-build\n`
    : "";

  return `# Agent Dockerfile for ${agentShortName} (role: ${roleShortName})
# Generated by mason chapter build
FROM ${baseImage}

WORKDIR /home/mason
${runtimeInstall}
# Copy pre-populated node_modules (all deps resolved by docker-init)
COPY node_modules/ /app/node_modules/
ENV PATH="/app/node_modules/.bin:$PATH"
${aptInstallStep}
# Create mason user with host-matching UID/GID
ARG HOST_UID=1000
ARG HOST_GID=1000
RUN (getent group $HOST_GID | cut -d: -f1 | xargs -r groupdel 2>/dev/null || true) \\
    && (getent passwd $HOST_UID | cut -d: -f1 | xargs -r userdel 2>/dev/null || true) \\
    && groupadd -g $HOST_GID mason && useradd -m -u $HOST_UID -g $HOST_GID mason \\
    && mkdir -p /home/mason/workspace/project /home/mason/.claude /home/mason/data /logs \\
    && chown -R mason:mason /home/mason /app /logs

# Copy materialized workspace files
${workspaceCopyLine}
RUN chown -R mason:mason /home/mason/workspace
${homeCopyLines}${homeBackupLine}
USER mason

WORKDIR /home/mason/workspace/project

# Unified entrypoint — reads agent-launch.json for runtime config
ENTRYPOINT ["agent-entry"]
`;
}

/**
 * Get runtime-specific Dockerfile install instructions.
 *
 * Each runtime may need its own install step (e.g., npm install -g),
 * but the entrypoint is always `agent-entry` which reads
 * `agent-launch.json` to know what command to run.
 */
function getRuntimeInstall(runtime: string): string {
  switch (runtime) {
    case "claude-code":
      return `
# Install claude-code runtime
RUN npm install -g @anthropic-ai/claude-code
`;

    case "pi-coding-agent":
      return `
# Install pi-coding-agent runtime
RUN npm install -g @mariozechner/pi-coding-agent
`;

    case "mcp-agent":
      return `
# Runtime: mcp-agent (uses @clawmasons/mcp-agent from node_modules)
`;

    default:
      return `
# Runtime: ${runtime} (no specific install)
`;
  }
}
