import type { ResolvedAgent, ResolvedRole } from "@clawmasons/shared";
import { getAppShortName } from "@clawmasons/shared";
import { ACP_RUNTIME_COMMANDS } from "../materializer/common.js";

/**
 * Generate a Dockerfile for an agent container scoped to a single role.
 *
 * The agent image is configured with the materialized workspace files
 * (generated by the runtime materializer) and expects a project directory
 * to be mounted at `/home/mason/workspace/project/`.
 *
 * All agent images run as `USER mason`.
 *
 * The generated Dockerfile uses `docker/` as its build context
 * (the Dockerfile lives at `docker/agent/<agent-name>/<role-name>/Dockerfile`).
 *
 * LLM provider API keys are NOT baked into the image — they are passed
 * at runtime via docker-compose environment variables.
 *
 * @param agent  The fully resolved agent.
 * @param role   The specific role for this agent image.
 */
export function generateAgentDockerfile(
  agent: ResolvedAgent,
  role: ResolvedRole,
  options?: { acpMode?: boolean },
): string {
  const agentShortName = getAppShortName(agent.name);
  const roleShortName = getAppShortName(role.name);

  // Determine the runtime — first runtime is the primary one
  const primaryRuntime = agent.runtimes[0] ?? "claude-code";

  const acpMode = options?.acpMode ?? false;

  // Build runtime-specific install and entrypoint
  const { runtimeInstall, runtimeEntrypoint } = getRuntimeConfig(primaryRuntime, acpMode);

  // Workspace files are COPY'd from a pre-generated directory
  // The workspace dir is created by docker-init at:
  //   docker/agent/<agent-short-name>/<role-short-name>/workspace/
  const workspaceCopyLine = `COPY agent/${agentShortName}/${roleShortName}/workspace/ /home/mason/workspace/`;

  const acpMarker = acpMode ? " [ACP mode]" : "";

  return `# Agent Dockerfile for ${agentShortName} (role: ${roleShortName})${acpMarker}
# Generated by chapter docker-init
FROM node:22-slim

WORKDIR /home/mason
${runtimeInstall}
# Copy pre-populated node_modules (all deps resolved by docker-init)
COPY node_modules/ /app/node_modules/

# Create mason user and set up directories
RUN groupadd -r mason && useradd -r -g mason -m mason \\
    && mkdir -p /home/mason/workspace/project /home/mason/data /logs \\
    && chown -R mason:mason /home/mason /app /logs

# Copy materialized workspace files
${workspaceCopyLine}
RUN chown -R mason:mason /home/mason/workspace

USER mason

WORKDIR /home/mason/workspace/project

${runtimeEntrypoint}
`;
}

/**
 * Get runtime-specific Dockerfile instructions.
 *
 * When `acpMode` is true, the entrypoint is switched to the ACP agent
 * command from `ACP_RUNTIME_COMMANDS`. If no mapping exists for the
 * runtime, the default entrypoint is used with a comment.
 */
function getRuntimeConfig(runtime: string, acpMode: boolean): {
  runtimeInstall: string;
  runtimeEntrypoint: string;
} {
  const baseConfig = getBaseRuntimeConfig(runtime);

  if (!acpMode) {
    return baseConfig;
  }

  const acpCommand = ACP_RUNTIME_COMMANDS[runtime];
  if (!acpCommand) {
    return {
      runtimeInstall: baseConfig.runtimeInstall,
      runtimeEntrypoint: `# ACP mode requested but no ACP command mapping for runtime "${runtime}"\n${baseConfig.runtimeEntrypoint}`,
    };
  }

  // Split the ACP command string into JSON array form for ENTRYPOINT
  const parts = acpCommand.split(" ");
  const entrypoint = JSON.stringify(parts);

  return {
    runtimeInstall: baseConfig.runtimeInstall,
    runtimeEntrypoint: `ENTRYPOINT ${entrypoint}`,
  };
}

/**
 * Get base runtime-specific Dockerfile instructions (non-ACP).
 */
function getBaseRuntimeConfig(runtime: string): {
  runtimeInstall: string;
  runtimeEntrypoint: string;
} {
  switch (runtime) {
    case "claude-code":
      return {
        runtimeInstall: `
# Install claude-code runtime
RUN npm install -g @anthropic-ai/claude-code
`,
        runtimeEntrypoint: `ENTRYPOINT ["claude"]`,
      };

    case "pi-coding-agent":
      return {
        runtimeInstall: `
# Install pi-coding-agent runtime
RUN npm install -g @mariozechner/pi-coding-agent
`,
        runtimeEntrypoint: `ENTRYPOINT ["pi"]`,
      };

    default:
      return {
        runtimeInstall: `
# Runtime: ${runtime} (no specific install)
`,
        runtimeEntrypoint: `ENTRYPOINT ["npx", "${runtime}"]`,
      };
  }
}
