/**
 * Generate a Dockerfile for the credential service container.
 *
 * The credential service resolves and distributes credentials to agents
 * through the MCP proxy via WebSocket. It uses the same base image and
 * build pattern as the proxy Dockerfile.
 *
 * All credential service images run as `USER mason`.
 *
 * The generated Dockerfile uses `docker/` as its build context
 * (the Dockerfile lives at `docker/credential-service/Dockerfile`).
 */
export function generateCredentialServiceDockerfile(): string {
  return `# Credential Service Dockerfile
# Generated by clawmasons docker-init
FROM node:22-slim

WORKDIR /app

# Install build tools for native addons (e.g., better-sqlite3)
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

# Copy pre-populated node_modules (all deps resolved by docker-init)
COPY package.json ./
COPY node_modules/ ./node_modules/

# Rebuild native addons for the container platform
RUN npm rebuild better-sqlite3

# Create mason user and set up directories
RUN groupadd -r mason && useradd -r -g mason -m mason \\
    && mkdir -p /home/mason/data /logs \\
    && chown -R mason:mason /app /home/mason/data /logs

USER mason

ENTRYPOINT ["node", "node_modules/.bin/credential-service"]
`;
}
