/**
 * Generate a Dockerfile for the shared proxy container.
 *
 * The proxy image boots via the esbuild-bundled `proxy-bundle.cjs` and
 * reads `proxy-config.json` at runtime (mounted via docker-compose volume).
 * No `node_modules/` or runtime package discovery needed.
 *
 * The mason user is created BEFORE COPY statements so that
 * `COPY --chown=mason:mason` avoids a duplicate `chown -R` layer.
 *
 * All proxy images run as `USER mason`.
 *
 * The generated Dockerfile uses `.mason/docker/mcp-proxy/` as its build
 * context (shared across all roles).
 */
export function generateProxyDockerfile(): string {
  return `# Shared proxy Dockerfile
# Generated by mason build
FROM node:22-slim

WORKDIR /app

# Cache V8-compiled bytecode across container restarts
ENV NODE_COMPILE_CACHE=/app/.cache/v8
# Direct npm/npx package cache into the persistent .cache volume
ENV NPM_CONFIG_CACHE=/app/.cache/npm

# Create mason user with host-matching UID/GID (before COPY for --chown)
ARG HOST_UID=1000
ARG HOST_GID=1000
RUN (getent group $HOST_GID | cut -d: -f1 | xargs -r groupdel 2>/dev/null || true) \\
    && (getent passwd $HOST_UID | cut -d: -f1 | xargs -r userdel 2>/dev/null || true) \\
    && groupadd -g $HOST_GID mason && useradd -m -u $HOST_UID -g $HOST_GID mason \\
    && mkdir -p /home/mason/data /logs /mason-logs /app/.cache/v8 /app/.cache/npm \\
    && chown -R mason:mason /home/mason/data /logs /mason-logs /app/.cache

# Copy esbuild-bundled proxy entry point (single file, fast boot)
COPY --chown=mason:mason proxy-bundle.cjs ./

USER mason

ENTRYPOINT ["node", "proxy-bundle.cjs"]
CMD ["--transport", "streamable-http"]
`;
}
