import type { ResolvedRole } from "@clawmasons/shared";
import { getAppShortName } from "@clawmasons/shared";

/**
 * Generate a Dockerfile for a proxy container that serves a single role.
 *
 * The proxy image reads `proxy-config.json` (generated at build time) and
 * boots via the esbuild-bundled `proxy-bundle.cjs`. No `node_modules/`
 * or runtime package discovery needed.
 *
 * The mason user is created BEFORE COPY statements so that
 * `COPY --chown=mason:mason` avoids a duplicate `chown -R` layer.
 *
 * All proxy images run as `USER mason`.
 *
 * The generated Dockerfile uses `docker/` as its build context
 * (the Dockerfile lives at `docker/<role-name>/mcp-proxy/Dockerfile`).
 *
 * @param role       The resolved role this proxy serves.
 * @param agentName  The agent package name (unused after config migration,
 *                   kept for call-site compatibility).
 */
export function generateProxyDockerfile(
  role: ResolvedRole,
): string {
  const roleShortName = getAppShortName(role.name);

  return `# Proxy Dockerfile for role: ${roleShortName}
# Generated by mason build
FROM node:22-slim

WORKDIR /app

# Cache V8-compiled bytecode across container restarts
ENV NODE_COMPILE_CACHE=/app/.cache/v8
# Direct npm/npx package cache into the persistent .cache volume
ENV NPM_CONFIG_CACHE=/app/.cache/npm

# Create mason user with host-matching UID/GID (before COPY for --chown)
ARG HOST_UID=1000
ARG HOST_GID=1000
RUN (getent group $HOST_GID | cut -d: -f1 | xargs -r groupdel 2>/dev/null || true) \\
    && (getent passwd $HOST_UID | cut -d: -f1 | xargs -r userdel 2>/dev/null || true) \\
    && groupadd -g $HOST_GID mason && useradd -m -u $HOST_UID -g $HOST_GID mason \\
    && mkdir -p /home/mason/data /logs /mason-logs /app/.cache/v8 /app/.cache/npm \\
    && chown -R mason:mason /home/mason/data /logs /mason-logs /app/.cache

# Copy esbuild-bundled proxy entry point (single file, fast boot)
COPY --chown=mason:mason proxy-bundle.cjs ./

# Copy pre-resolved proxy config (generated at build time)
COPY --chown=mason:mason ${roleShortName}/mcp-proxy/proxy-config.json ./

USER mason

ENTRYPOINT ["node", "proxy-bundle.cjs"]
CMD ["--transport", "streamable-http"]
`;
}
