import type { ResolvedRole } from "@clawmasons/shared";
import { getAppShortName } from "@clawmasons/shared";

/**
 * Generate a Dockerfile for a proxy container that serves a single role.
 *
 * The proxy image installs all mason packages from the local
 * `docker/node_modules/` build context (no registry pulls).  It boots
 * `mason proxy` configured for the given agent, which discovers
 * packages at runtime from node_modules/.
 *
 * All proxy images run as `USER mason`.
 *
 * The generated Dockerfile uses `docker/` as its build context
 * (the Dockerfile lives at `docker/proxy/<role-name>/Dockerfile`).
 *
 * @param role       The resolved role this proxy serves.
 * @param agentName  The agent package name (passed to `mason proxy --agent`).
 */
export function generateProxyDockerfile(
  role: ResolvedRole,
  agentName: string,
): string {
  const roleShortName = getAppShortName(role.name);

  return `# Proxy Dockerfile for role: ${roleShortName}
# Generated by mason build
FROM node:22-slim

WORKDIR /app

# Cache V8-compiled bytecode across container restarts
ENV NODE_COMPILE_CACHE=/app/.cache/v8
# Direct npm/npx package cache into the persistent .cache volume
ENV NPM_CONFIG_CACHE=/app/.cache/npm

# Copy esbuild-bundled proxy entry point (single file, fast boot)
COPY proxy-bundle.cjs ./

# Copy pre-populated node_modules (package.json for discovery)
COPY package.json ./
COPY node_modules/ ./node_modules/

# Create mason user with host-matching UID/GID
ARG HOST_UID=1000
ARG HOST_GID=1000
RUN (getent group $HOST_GID | cut -d: -f1 | xargs -r groupdel 2>/dev/null || true) \\
    && (getent passwd $HOST_UID | cut -d: -f1 | xargs -r userdel 2>/dev/null || true) \\
    && groupadd -g $HOST_GID mason && useradd -m -u $HOST_UID -g $HOST_GID mason \\
    && mkdir -p /home/mason/data /logs /mason-logs /app/.cache/v8 /app/.cache/npm \\
    && chown -R mason:mason /app /home/mason/data /logs /mason-logs

USER mason

ENTRYPOINT ["node", "proxy-bundle.cjs"]
CMD ["--agent", "${agentName}", "--transport", "streamable-http"]
`;
}
