import { CLI_NAME_LOWERCASE } from "@clawmasons/shared";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import type { RuntimeMaterializer, MaterializationResult } from "@clawmasons/agent-sdk";
import type { ResolvedAgent } from "@clawmasons/shared";
import { stringify as tomlStringify } from "smol-toml";

/**
 * Generate `.codex/config.toml` content with MCP proxy configuration.
 *
 * Creates a `[mcp_servers.mason]` section pointing at the mason proxy endpoint.
 * Uses `/mcp` for streamable-http or `/sse` for SSE based on proxy type.
 */
export function generateConfigToml(
  proxyEndpoint: string,
  proxyType: "sse" | "streamable-http",
): string {
  const pathSuffix = proxyType === "sse" ? "/sse" : "/mcp";

  const config = {
    mcp_servers: {
      [CLI_NAME_LOWERCASE]: {
        url: `${proxyEndpoint}${pathSuffix}`,
        bearer_token_env_var: "MCP_PROXY_TOKEN",
      },
    },
  };

  return `# Generated by mason codex-agent materializer\n\n${tomlStringify(config)}\n`;
}

export const codexAgentMaterializer: RuntimeMaterializer = {
  name: "codex-agent",

  /**
   * Materialize home directory files for the Codex agent.
   *
   * Copies `~/.codex/auth.json` from the host if it exists.
   * The MCP config (`.codex/config.toml`) is generated by `materializeWorkspace`
   * since it requires the proxy endpoint, which is not available here.
   */
  materializeHome(projectDir: string, homePath: string): void {
    const hostHome = os.homedir();

    // Copy ~/.codex/auth.json if it exists on the host
    const hostAuthJson = path.join(hostHome, ".codex", "auth.json");
    if (fs.existsSync(hostAuthJson)) {
      const codexDir = path.join(homePath, ".codex");
      fs.mkdirSync(codexDir, { recursive: true });
      fs.copyFileSync(hostAuthJson, path.join(codexDir, "auth.json"));
    }
  },

  materializeWorkspace(
    agent: ResolvedAgent,
    proxyEndpoint: string,
  ): MaterializationResult {
    const result: MaterializationResult = new Map();
    const proxyType = agent.proxy?.type ?? "sse";

    // .codex/config.toml — MCP server configuration (project-scoped)
    result.set(".codex/config.toml", generateConfigToml(proxyEndpoint, proxyType));

    return result;
  },
};
