import { CLI_NAME_LOWERCASE, getAppShortName } from "@clawmasons/shared";
import * as fs from "node:fs";
import * as path from "node:path";
import * as os from "node:os";
import type { RuntimeMaterializer, MaterializationResult, MaterializeOptions, AgentPackage } from "@clawmasons/agent-sdk";
import { collectAllTasks, collectAllSkills, materializeTasks, materializeSkills, generateAgentLaunchJson } from "@clawmasons/agent-sdk";
import type { ResolvedAgent } from "@clawmasons/shared";
import { stringify as tomlStringify } from "smol-toml";

/**
 * Generate `.codex/config.toml` content with MCP proxy configuration.
 *
 * Creates a `[mcp_servers.mason]` section pointing at the mason proxy endpoint.
 * Uses `/mcp` for streamable-http or `/sse` for SSE based on proxy type.
 */
export function generateConfigToml(
  proxyEndpoint: string,
  proxyType: "sse" | "streamable-http",
): string {
  const pathSuffix = proxyType === "sse" ? "/sse" : "/mcp";

  const config = {
    ...(proxyType === "streamable-http" ? { experimental_use_rmcp_client: true } : {}),
    mcp_servers: {
      [CLI_NAME_LOWERCASE]: {
        url: `${proxyEndpoint}${pathSuffix}`,
        bearer_token_env_var: "MCP_PROXY_TOKEN",
      },
    },
  };

  return `# Generated by mason codex-agent materializer\n\n${tomlStringify(config)}\n`;
}

/** The mcpNameTemplate for Codex: `${server}_${tool}` */
const MCP_NAME_TEMPLATE = "${server}_${tool}";

/**
 * Generate a workspace-level `AGENTS.md` containing role instructions,
 * task references, skill references, and MCP tool list.
 */
export function generateAgentsMd(agent: ResolvedAgent): string {
  const lines: string[] = [];
  const role = agent.roles[0];
  const roleName = role ? getAppShortName(role.name) : "unknown";

  lines.push("# Agent Instructions");
  lines.push("");
  lines.push(`You are operating as a mason agent with the role: ${roleName}.`);
  lines.push("");

  // Available tasks as /prompts:<taskName> references
  const allTasks = collectAllTasks(agent.roles);
  if (allTasks.length > 0) {
    lines.push("## Available Tasks");
    lines.push("The following tasks are available as custom prompts:");
    for (const [task] of allTasks) {
      const desc = task.description ?? task.name;
      lines.push(`- /prompts:${task.name} — ${desc}`);
    }
    lines.push("");
  }

  // Available skills pointing to .agents/skills/
  const allSkills = collectAllSkills(agent.roles);
  if (allSkills.size > 0) {
    lines.push("## Available Skills");
    for (const [skillName, skill] of allSkills) {
      const shortName = getAppShortName(skillName);
      const desc = skill.description ? `: ${skill.description}` : "";
      lines.push(`- ${shortName}${desc} — See .agents/skills/${shortName}/`);
    }
    lines.push("");
  }

  // MCP tool list with rewritten names
  const toolLines: string[] = [];
  for (const r of agent.roles) {
    for (const [appName, perms] of Object.entries(r.permissions)) {
      const serverName = getAppShortName(appName);
      for (const tool of perms.allow) {
        const rewritten = MCP_NAME_TEMPLATE
          .replace("${server}", serverName)
          .replace("${tool}", tool);
        toolLines.push(`- ${rewritten}`);
      }
    }
  }
  // Deduplicate tool lines
  const uniqueTools = [...new Set(toolLines)];
  if (uniqueTools.length > 0) {
    lines.push("## MCP Tools");
    lines.push("Tools are provided via the mason MCP server. Available tools:");
    for (const tl of uniqueTools) lines.push(tl);
    lines.push("");
    lines.push("Only use tools from this list.");
  }

  return lines.join("\n");
}

/** Reference to the parent AgentPackage — set after construction. */
let _agentPkg: AgentPackage;

export const codexAgentMaterializer: RuntimeMaterializer = {
  name: "codex-agent",

  /**
   * Materialize home directory files for the Codex agent.
   *
   * Copies `~/.codex/auth.json` from the host if it exists.
   * The MCP config (`.codex/config.toml`) is generated by `materializeWorkspace`
   * since it requires the proxy endpoint, which is not available here.
   */
  materializeHome(projectDir: string, homePath: string): void {
    const hostHome = os.homedir();
    const codexDir = path.join(homePath, ".codex");
    fs.mkdirSync(codexDir, { recursive: true });

    // Copy ~/.codex/auth.json if it exists on the host
    const hostAuthJson = path.join(hostHome, ".codex", "auth.json");
    if (fs.existsSync(hostAuthJson)) {
      fs.copyFileSync(hostAuthJson, path.join(codexDir, "auth.json"));
    }

    // Write trusted project config so codex doesn't prompt for approval
    const configContent = `[projects."/home/mason/workspace/project"]\ntrust_level = "trusted"\n`;
    fs.writeFileSync(path.join(codexDir, "config.toml"), configContent);
  },

  materializeWorkspace(
    agent: ResolvedAgent,
    proxyEndpoint: string,
    _proxyToken?: string,
    options?: MaterializeOptions,
    existingHomePath?: string,
  ): MaterializationResult {
    const result: MaterializationResult = new Map();
    const proxyType = agent.proxy?.type ?? "sse";

    // .codex/config.toml — MCP server configuration (project-scoped)
    result.set(".codex/config.toml", generateConfigToml(proxyEndpoint, proxyType));

    // .codex/prompts/*.md — task conversion via SDK helper
    // Written to home directory so Codex finds them at ~/.codex/prompts/
    if (_agentPkg?.tasks) {
      const allTasks = collectAllTasks(agent.roles);
      const tasksWithDefaults = allTasks.map(([t]) => ({
        ...t,
        description: t.description || t.name,
      }));
      const taskFiles = materializeTasks(
        tasksWithDefaults,
        _agentPkg.tasks,
        _agentPkg.mcpNameTemplate,
      );
      if (existingHomePath) {
        for (const [p, c] of taskFiles) {
          const fullPath = path.join(existingHomePath, p);
          fs.mkdirSync(path.dirname(fullPath), { recursive: true });
          fs.writeFileSync(fullPath, c);
        }
      } else {
        for (const [p, c] of taskFiles) result.set(p, c);
      }
    }

    // .agents/skills/{skillName}/ — skill conversion via SDK helper
    if (_agentPkg?.skills) {
      const allSkills = collectAllSkills(agent.roles);
      const skillFiles = materializeSkills(
        [...allSkills.values()],
        _agentPkg.skills,
        _agentPkg.mcpNameTemplate,
      );
      for (const [p, c] of skillFiles) result.set(p, c);
    }

    // AGENTS.md — role instructions
    result.set("AGENTS.md", generateAgentsMd(agent));

    // agent-launch.json — tells agent-entry how to bootstrap this agent
    result.set(
      "agent-launch.json",
      generateAgentLaunchJson(
        _agentPkg,
        agent.credentials,
        options?.acpMode,
        undefined,
        options?.agentArgs,
        options?.initialPrompt,
        options?.printMode,
      ),
    );

    return result;
  },
};

/**
 * Set the parent AgentPackage reference (called during package initialization).
 * @internal
 */
export function _setAgentPackage(pkg: AgentPackage): void {
  _agentPkg = pkg;
}
