import { describe, it, expect, beforeEach, afterEach, vi } from "vitest";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { program } from "../../src/cli/index.js";
import {
  resolveRoleForInit,
  generateInitRoleComposeYml,
  initRole,
} from "../../src/cli/commands/init-role.js";
import type { DiscoveredPackage, ResolvedRole } from "@clawmasons/shared";

// ── Helpers ──────────────────────────────────────────────────────────────

function makeRolePackage(): DiscoveredPackage {
  return {
    name: "@test/role-writer",
    version: "1.0.0",
    packagePath: "/fake/role",
    chapterField: {
      type: "role" as const,
      risk: "LOW" as const,
      permissions: {
        "@test/app-github": { allow: ["create_pr"], deny: [] },
      },
    },
  } as DiscoveredPackage;
}

function makeResolvedRole(name: string): ResolvedRole {
  return {
    name,
    version: "1.0.0",
    risk: "LOW" as const,
    permissions: {
      "@test/app-github": { allow: ["create_pr"], deny: [] },
    },
    tasks: [],
    apps: [],
    skills: [],
  };
}

// ── Command Registration ─────────────────────────────────────────────────

describe("CLI init-role command", () => {
  it("has the init-role command registered under chapter", () => {
    const chapterCmd = program.commands.find((c) => c.name() === "chapter");
    expect(chapterCmd).toBeDefined();
    const cmd = chapterCmd!.commands.find((c) => c.name() === "init-role");
    expect(cmd).toBeDefined();
    if (cmd) {
      expect(cmd.description()).toContain("host-wide runtime");
    }
  });
});

// ── resolveRoleForInit ─────────────────────────────────────────────────

describe("resolveRoleForInit", () => {
  it("finds a matching role package", () => {
    const packages = new Map<string, DiscoveredPackage>([
      ["@test/role-writer", makeRolePackage()],
    ]);

    const resolveFn = () => makeResolvedRole("@test/role-writer");

    const result = resolveRoleForInit(
      "@test/role-writer",
      packages,
      resolveFn,
    );

    expect(result.shortName).toBe("writer");
    expect(result.resolved.roles).toHaveLength(1);
  });

  it("throws when role not found", () => {
    const packages = new Map<string, DiscoveredPackage>();

    const resolveFn = () => makeResolvedRole("@test/role-writer");

    expect(() =>
      resolveRoleForInit("@test/role-writer", packages, resolveFn),
    ).toThrow('Role "@test/role-writer" not found');
  });
});

// ── generateInitRoleComposeYml ───────────────────────────────────────────

describe("generateInitRoleComposeYml", () => {
  it("generates correct YAML with env var substitution", () => {
    const yaml = generateInitRoleComposeYml({
      dockerBuildPath: "/path/to/docker",
      agents: [{ name: "@test/role-writer", shortName: "role-writer" }],
      role: "@test/role-writer",
      roleShortName: "writer",
    });

    expect(yaml).toContain("# Generated by clawmasons init-role");
    expect(yaml).toContain("proxy-writer:");
    expect(yaml).toContain("credential-service:");
    expect(yaml).toContain("agent-role-writer-writer:");
    expect(yaml).toContain('context: "/path/to/docker"');
    expect(yaml).toContain('dockerfile: "proxy/writer/Dockerfile"');
    expect(yaml).toContain('dockerfile: "credential-service/Dockerfile"');
    expect(yaml).toContain("${PROJECT_DIR}:/workspace");
    expect(yaml).toContain("CHAPTER_PROXY_TOKEN=${CHAPTER_PROXY_TOKEN}");
    expect(yaml).toContain(
      "CREDENTIAL_PROXY_TOKEN=${CREDENTIAL_PROXY_TOKEN}",
    );
    expect(yaml).toContain("MCP_PROXY_TOKEN=${CHAPTER_PROXY_TOKEN}");
    expect(yaml).toContain("init: true");
  });

  it("includes role mounts in agent volumes", () => {
    const yaml = generateInitRoleComposeYml({
      dockerBuildPath: "/path/to/docker",
      agents: [{ name: "@test/role-writer", shortName: "role-writer" }],
      role: "@test/role-writer",
      roleShortName: "writer",
      roleMounts: [
        { source: "/host/data", target: "/container/data", readonly: false },
      ],
    });

    const agentSection = yaml.split("agent-role-writer-writer:")[1]!;
    expect(agentSection).toContain('"/host/data:/container/data"');
    expect(agentSection).toContain("${PROJECT_DIR}:/workspace");
  });

  it("appends :ro for readonly role mounts", () => {
    const yaml = generateInitRoleComposeYml({
      dockerBuildPath: "/path/to/docker",
      agents: [{ name: "@test/role-writer", shortName: "role-writer" }],
      role: "@test/role-writer",
      roleShortName: "writer",
      roleMounts: [
        { source: "/configs", target: "/etc/app", readonly: true },
      ],
    });

    const agentSection = yaml.split("agent-role-writer-writer:")[1]!;
    expect(agentSection).toContain('"/configs:/etc/app:ro"');
  });

  it("does not add role mounts to proxy volumes", () => {
    const yaml = generateInitRoleComposeYml({
      dockerBuildPath: "/path/to/docker",
      agents: [{ name: "@test/role-writer", shortName: "role-writer" }],
      role: "@test/role-writer",
      roleShortName: "writer",
      roleMounts: [
        { source: "/host/data", target: "/mnt/data", readonly: false },
      ],
    });

    const proxySection = yaml.split("credential-service:")[0]!;
    expect(proxySection).not.toContain("/mnt/data");
  });
});

// ── initRole ─────────────────────────────────────────────────────────────

describe("initRole", () => {
  let tmpDir: string;
  let homeDir: string;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let exitSpy: any;

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "chapter-init-role-test-"));
    homeDir = path.join(tmpDir, "clawmasons-home");
    fs.mkdirSync(homeDir, { recursive: true });

    // Create docker/ directory to simulate a built workspace
    fs.mkdirSync(path.join(tmpDir, "docker"), { recursive: true });

    exitSpy = vi.spyOn(process, "exit").mockImplementation(() => {
      throw new Error("process.exit called");
    });
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    exitSpy.mockRestore();
  });

  function makeDeps(overrides?: Partial<Parameters<typeof initRole>[2]>) {
    const packages = new Map<string, DiscoveredPackage>([
      ["@test/role-writer", makeRolePackage()],
    ]);

    return {
      discoverPackagesFn: () => packages,
      resolveRoleFn: () => makeResolvedRole("@test/role-writer"),
      readChapterConfigFn: () => ({ chapter: "acme.platform" }),
      getClawmasonsHomeFn: () => homeDir,
      ...overrides,
    };
  }

  it("creates role directory and docker-compose.yaml", async () => {
    await initRole(tmpDir, { role: "@test/role-writer" }, makeDeps());

    const roleDir = path.join(homeDir, "acme", "platform", "writer");
    expect(fs.existsSync(roleDir)).toBe(true);
    expect(
      fs.existsSync(path.join(roleDir, "docker-compose.yaml")),
    ).toBe(true);

    const content = fs.readFileSync(
      path.join(roleDir, "docker-compose.yaml"),
      "utf-8",
    );
    expect(content).toContain("# Generated by clawmasons init-role");
    expect(content).toContain("proxy-writer:");
  });

  it("updates chapters.json", async () => {
    await initRole(tmpDir, { role: "@test/role-writer" }, makeDeps());

    const chaptersPath = path.join(homeDir, "chapters.json");
    expect(fs.existsSync(chaptersPath)).toBe(true);

    const data = JSON.parse(fs.readFileSync(chaptersPath, "utf-8"));
    expect(data.chapters).toHaveLength(1);
    expect(data.chapters[0].lodge).toBe("acme");
    expect(data.chapters[0].chapter).toBe("platform");
    expect(data.chapters[0].role).toBe("writer");
  });

  it("uses --target-dir for custom path", async () => {
    const customDir = path.join(tmpDir, "custom-role-dir");

    await initRole(
      tmpDir,
      { role: "@test/role-writer", targetDir: customDir },
      makeDeps(),
    );

    expect(fs.existsSync(path.join(customDir, "docker-compose.yaml"))).toBe(
      true,
    );

    // chapters.json should record the targetDir
    const chaptersPath = path.join(homeDir, "chapters.json");
    const data = JSON.parse(fs.readFileSync(chaptersPath, "utf-8"));
    expect(data.chapters[0].targetDir).toBe(customDir);
    expect(data.chapters[0].roleDir).toBe(customDir);
  });

  it("backs up existing docker-compose.yaml", async () => {
    // First init
    await initRole(tmpDir, { role: "@test/role-writer" }, makeDeps());

    const roleDir = path.join(homeDir, "acme", "platform", "writer");
    const composeFile = path.join(roleDir, "docker-compose.yaml");
    const originalContent = fs.readFileSync(composeFile, "utf-8");

    // Second init -- should create backup
    await initRole(tmpDir, { role: "@test/role-writer" }, makeDeps());

    const backupFile = path.join(roleDir, "docker-compose.yaml.bak");
    expect(fs.existsSync(backupFile)).toBe(true);
    expect(fs.readFileSync(backupFile, "utf-8")).toBe(originalContent);
  });

  it("creates logs directory", async () => {
    await initRole(tmpDir, { role: "@test/role-writer" }, makeDeps());

    const logsDir = path.join(
      homeDir,
      "acme",
      "platform",
      "writer",
      "logs",
    );
    expect(fs.existsSync(logsDir)).toBe(true);
  });

  it("ensures CLAWMASONS_HOME/.gitignore exists", async () => {
    await initRole(tmpDir, { role: "@test/role-writer" }, makeDeps());

    const gitignorePath = path.join(homeDir, ".gitignore");
    expect(fs.existsSync(gitignorePath)).toBe(true);
    const content = fs.readFileSync(gitignorePath, "utf-8");
    expect(content).toContain("**/logs/");
  });

  it("fails when docker build directory is missing", async () => {
    // Remove the docker directory
    fs.rmSync(path.join(tmpDir, "docker"), { recursive: true, force: true });

    await expect(
      initRole(tmpDir, { role: "@test/role-writer" }, makeDeps()),
    ).rejects.toThrow("process.exit called");
  });
});
