import type { ResolvedAgent, ResolvedRole, ResolvedTask } from "@clawmasons/shared";
import { getAppShortName } from "@clawmasons/shared";
import type { RuntimeMaterializer, MaterializationResult, MaterializeOptions, AgentPackage } from "@clawmasons/agent-sdk";
import {
  formatPermittedTools,
  collectAllSkills,
  collectAllTasks,
  generateAgentsMd,
  generateSkillReadme,
  generateAgentLaunchJson,
} from "@clawmasons/agent-sdk";

/**
 * Generate the command prompt for a pi `registerCommand()` call.
 *
 * Same structure as claude-code's slash commands:
 * - Role context with permitted tools
 * - Skill references
 * - Task prompt
 */
function generateCommandPrompt(
  task: ResolvedTask,
  owningRoles: ResolvedRole[],
): string {
  const lines: string[] = [];

  for (const role of owningRoles) {
    const roleShortName = getAppShortName(role.name);
    lines.push("## Role Context");
    lines.push(`You are operating as role: ${roleShortName}`);
    lines.push("Permitted tools for this role:");
    lines.push(formatPermittedTools(role.permissions));
    lines.push("Do NOT use tools outside this list even if they appear available.");
    lines.push("");
  }

  if (task.skills.length > 0) {
    lines.push("## Required Skills");
    for (const skill of task.skills) {
      const skillShortName = getAppShortName(skill.name);
      lines.push(`See skills/${skillShortName}/ for ${skill.description}.`);
    }
    lines.push("");
  }

  lines.push("## Task");
  if (task.prompt) {
    lines.push(`[contents of ${task.prompt}]`);
  } else {
    lines.push("[no prompt defined]");
  }

  return lines.join("\n");
}

/**
 * Escape a string for use inside a JavaScript template literal.
 * Escapes backticks and ${} expressions.
 */
function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Generate .pi/settings.json content.
 *
 * Declares the active model using pi's model ID format:
 * {provider}/{model} (e.g., "openrouter/anthropic/claude-sonnet-4")
 */
function generatePiSettingsJson(agent: ResolvedAgent): string {
  if (!agent.llm) {
    throw new Error(
      `Pi-coding-agent materializer requires llm configuration on agent "${agent.name}". ` +
      `Specify llm.provider and llm.model in the agent's package.json chapter field.`,
    );
  }

  const modelId = `${agent.llm.provider}/${agent.llm.model}`;
  return JSON.stringify({ model: modelId }, null, 2);
}

/**
 * Generate .pi/mcp.json content.
 *
 * Creates a single "chapter" MCP server entry pointing at the proxy's
 * unified endpoint:  /sse  (SSE)  or  /mcp  (streamable-http).
 */
function generatePiMcpJson(
  proxyEndpoint: string,
  proxyType: "sse" | "streamable-http",
  proxyToken?: string,
): string {
  const pathSuffix = proxyType === "sse" ? "/sse" : "/mcp";
  const bearerValue = proxyToken
    ? `Bearer ${proxyToken}`
    : "Bearer ${MCP_PROXY_TOKEN}";

  const mcpConfig = {
    mcpServers: {
      chapter: {
        type: proxyType,
        url: `${proxyEndpoint}${pathSuffix}`,
        headers: {
          Authorization: bearerValue,
        },
      },
    },
  };

  return JSON.stringify(mcpConfig, null, 2);
}

/**
 * Generate .pi/extensions/chapter-mcp/package.json content.
 */
function generateExtensionPackageJson(): string {
  return JSON.stringify(
    {
      name: "chapter-mcp",
      version: "1.0.0",
      type: "module",
      main: "index.ts",
    },
    null,
    2,
  );
}

/**
 * Generate .pi/extensions/chapter-mcp/index.ts content.
 *
 * Creates a pi extension that registers each chapter task as a pi command.
 * MCP server configuration lives in .pi/mcp.json (not in extension code).
 */
function generateExtensionIndexTs(
  agent: ResolvedAgent,
): string {
  const lines: string[] = [];
  lines.push("// Generated by the pi-coding-agent materializer");
  lines.push("export default (pi) => {");

  // Register each task as a pi command
  const allTasks = collectAllTasks(agent.roles);
  for (const [task, owningRoles] of allTasks) {
    const taskShortName = getAppShortName(task.name);
    const description = `${task.name}@${task.version}`;
    const prompt = generateCommandPrompt(task, owningRoles);

    lines.push("");
    lines.push("  pi.registerCommand({");
    lines.push(`    name: "${taskShortName}",`);
    lines.push(`    description: "${escapeTemplateLiteral(description)}",`);
    lines.push(`    prompt: \`${escapeTemplateLiteral(prompt)}\`,`);
    lines.push("  });");
  }

  lines.push("};");

  return lines.join("\n");
}

/** Reference to the parent AgentPackage — set after construction. */
let _agentPkg: AgentPackage;

export const piCodingAgentMaterializer: RuntimeMaterializer = {
  name: "pi-coding-agent",

  materializeWorkspace(
    agent: ResolvedAgent,
    proxyEndpoint: string,
    proxyToken?: string,
    options?: MaterializeOptions,
  ): MaterializationResult {
    const result: MaterializationResult = new Map();

    // AGENTS.md — agent identity and role docs (shared with claude-code)
    result.set("AGENTS.md", generateAgentsMd(agent));

    // .pi/settings.json — model configuration
    result.set(".pi/settings.json", generatePiSettingsJson(agent));

    // .pi/mcp.json — MCP server config
    const proxyType = agent.proxy?.type ?? "sse";
    result.set(
      ".pi/mcp.json",
      generatePiMcpJson(proxyEndpoint, proxyType, proxyToken),
    );

    // .pi/extensions/chapter-mcp/package.json
    result.set(
      ".pi/extensions/chapter-mcp/package.json",
      generateExtensionPackageJson(),
    );

    // .pi/extensions/chapter-mcp/index.ts — task commands
    result.set(
      ".pi/extensions/chapter-mcp/index.ts",
      generateExtensionIndexTs(agent),
    );

    // skills/{skill-short-name}/README.md
    const allSkills = collectAllSkills(agent.roles);
    for (const [, skill] of allSkills) {
      const skillShortName = getAppShortName(skill.name);
      result.set(
        `skills/${skillShortName}/README.md`,
        generateSkillReadme(skill),
      );
    }

    // agent-launch.json — tells agent-entry how to bootstrap this agent
    result.set(
      "agent-launch.json",
      generateAgentLaunchJson(_agentPkg, agent.credentials, options?.acpMode),
    );

    return result;
  },
};

/**
 * Set the parent AgentPackage reference (called during package initialization).
 * @internal
 */
export function _setAgentPackage(pkg: AgentPackage): void {
  _agentPkg = pkg;
}
