import type { ResolvedAgent } from "@clawmasons/shared";
import { getAppShortName, CLI_NAME_LOWERCASE } from "@clawmasons/shared";
import type { RuntimeMaterializer, MaterializationResult, MaterializeOptions, AgentPackage } from "@clawmasons/agent-sdk";
import {
  collectAllSkills,
  collectAllTasks,
  materializeTasks,
  materializeSkills,
  generateAgentLaunchJson,
} from "@clawmasons/agent-sdk";

/**
 * Escape a string for use inside a JavaScript template literal.
 * Escapes backticks and ${} expressions.
 */
function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Generate .pi/settings.json content.
 *
 * Declares the active model using pi's model ID format:
 * {provider}/{model} (e.g., "openrouter/anthropic/claude-sonnet-4")
 */
function generatePiSettingsJson(agent: ResolvedAgent): string {
  if (!agent.llm) {
    throw new Error(
      `Pi-coding-agent materializer requires llm configuration on agent "${agent.name}". ` +
      `Specify llm.provider and llm.model in the agent's package.json ${CLI_NAME_LOWERCASE} field.`,
    );
  }

  const modelId = `${agent.llm.provider}/${agent.llm.model}`;
  return JSON.stringify({ model: modelId }, null, 2);
}

/**
 * Generate .pi/mcp.json content.
 *
 * Creates a single MCP server entry (keyed by CLI_NAME_LOWERCASE) pointing at the proxy's
 * unified endpoint:  /sse  (SSE)  or  /mcp  (streamable-http).
 */
function generatePiMcpJson(
  proxyEndpoint: string,
  proxyType: "sse" | "streamable-http",
  proxyToken?: string,
): string {
  const pathSuffix = proxyType === "sse" ? "/sse" : "/mcp";
  const bearerValue = proxyToken
    ? `Bearer ${proxyToken}`
    : "Bearer ${MCP_PROXY_TOKEN}";

  const mcpConfig = {
    mcpServers: {
      [CLI_NAME_LOWERCASE]: {
        type: proxyType,
        url: `${proxyEndpoint}${pathSuffix}`,
        headers: {
          Authorization: bearerValue,
        },
      },
    },
  };

  return JSON.stringify(mcpConfig, null, 2);
}

/**
 * Generate .pi/extensions/{name}-mcp/package.json content.
 */
function generateExtensionPackageJson(): string {
  return JSON.stringify(
    {
      name: `${CLI_NAME_LOWERCASE}-mcp`,
      version: "1.0.0",
      type: "module",
      main: "index.ts",
    },
    null,
    2,
  );
}

/**
 * Generate .pi/extensions/{name}-mcp/index.ts content.
 *
 * Creates a pi extension that registers each task as a pi command.
 * MCP server configuration lives in .pi/mcp.json (not in extension code).
 */
function generateExtensionIndexTs(
  agent: ResolvedAgent,
): string {
  const lines: string[] = [];
  lines.push(`// Generated by the ${CLI_NAME_LOWERCASE} pi-coding-agent materializer`);
  lines.push("export default (pi) => {");

  // Register each task as a pi command
  const allTasks = collectAllTasks(agent.roles);
  for (const [task] of allTasks) {
    const taskShortName = getAppShortName(task.name);
    const description = `${task.name}@${task.version}`;
    const prompt = task.prompt ?? "[no prompt defined]";

    const safeName = taskShortName.replace(/"/g, '\\"');
    const safeDesc = description.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

    lines.push("");
    lines.push(`  pi.registerCommand("${safeName}", {`);
    lines.push(`    description: "${safeDesc}",`);
    lines.push(`    handler: async (args, ctx) => {`);
    lines.push(`      pi.sendUserMessage(\`${escapeTemplateLiteral(prompt)}\`);`);
    lines.push(`    },`);
    lines.push("  });");
  }

  lines.push("};");

  return lines.join("\n");
}

/** Reference to the parent AgentPackage — set after construction. */
let _agentPkg: AgentPackage;

export const piCodingAgentMaterializer: RuntimeMaterializer = {
  name: "pi-coding-agent",

  materializeWorkspace(
    agent: ResolvedAgent,
    proxyEndpoint: string,
    proxyToken?: string,
    options?: MaterializeOptions,
  ): MaterializationResult {
    const result: MaterializationResult = new Map();

    // .pi/settings.json — model configuration
    result.set(".pi/settings.json", generatePiSettingsJson(agent));

    // .pi/mcp.json — MCP server config
    const proxyType = agent.proxy?.type ?? "sse";
    result.set(
      ".pi/mcp.json",
      generatePiMcpJson(proxyEndpoint, proxyType, proxyToken),
    );

    // .pi/extensions/{name}-mcp/package.json
    result.set(
      `.pi/extensions/${CLI_NAME_LOWERCASE}-mcp/package.json`,
      generateExtensionPackageJson(),
    );

    // .pi/extensions/{name}-mcp/index.ts — task commands
    result.set(
      `.pi/extensions/${CLI_NAME_LOWERCASE}-mcp/index.ts`,
      generateExtensionIndexTs(agent),
    );

    // Skills — copy actual SKILL.md + companions via materializeSkills
    if (_agentPkg.skills) {
      const allSkills = collectAllSkills(agent.roles);
      const skillFiles = materializeSkills([...allSkills.values()], _agentPkg.skills);
      for (const [p, c] of skillFiles) result.set(p, c);
    }

    // .pi/APPEND_SYSTEM.md — role instructions into system prompt
    const instructions = agent.roles[0]?.instructions;
    if (instructions) {
      result.set(".pi/APPEND_SYSTEM.md", instructions);
    }

    // .pi/prompts/ — task markdown files
    if (_agentPkg.tasks) {
      const allTasks = collectAllTasks(agent.roles);
      const taskFiles = materializeTasks(allTasks.map(([t]) => t), _agentPkg.tasks);
      for (const [p, c] of taskFiles) result.set(p, c);
    }

    // agent-launch.json — tells agent-entry how to bootstrap this agent
    result.set(
      "agent-launch.json",
      generateAgentLaunchJson(_agentPkg, agent.credentials, options?.acpMode, undefined, options?.agentArgs, options?.initialPrompt),
    );

    return result;
  },
};

/**
 * Set the parent AgentPackage reference (called during package initialization).
 * @internal
 */
export function _setAgentPackage(pkg: AgentPackage): void {
  _agentPkg = pkg;
}
