import type { ResolvedAgent } from "@clawmasons/shared";
import { getAppShortName, CLI_NAME_LOWERCASE, convertMcpFormat } from "@clawmasons/shared";
import type { RuntimeMaterializer, MaterializationResult, MaterializeOptions, AgentPackage } from "@clawmasons/agent-sdk";
import {
  collectAllSkills,
  collectAllTasks,
  materializeTasks,
  materializeSkills,
  generateAgentLaunchJson,
} from "@clawmasons/agent-sdk";

/**
 * Escape a string for use inside a JavaScript template literal.
 * Escapes backticks and ${} expressions.
 */
function escapeTemplateLiteral(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

/**
 * Generate .pi/settings.json content.
 *
 * Declares the active model using pi's model ID format:
 * {provider}/{model} (e.g., "openrouter/anthropic/claude-sonnet-4")
 */
function generatePiSettingsJson(agent: ResolvedAgent): string {
  if (!agent.llm) {
    throw new Error(
      `Pi-coding-agent materializer requires llm configuration on agent "${agent.name}". ` +
      `Specify llm.provider and llm.model in the agent's package.json ${CLI_NAME_LOWERCASE} field.`,
    );
  }

  const modelId = `${agent.llm.provider}/${agent.llm.model}`;
  return JSON.stringify({ model: modelId }, null, 2);
}

/**
 * Generate .pi/mcp.json content.
 *
 * Creates a single MCP server entry (keyed by CLI_NAME_LOWERCASE) pointing at the proxy's
 * unified endpoint:  /sse  (SSE)  or  /mcp  (streamable-http).
 */
function generatePiMcpJson(
  proxyEndpoint: string,
  proxyType: "sse" | "streamable-http",
  proxyToken?: string,
): string {
  const pathSuffix = proxyType === "sse" ? "/sse" : "/mcp";
  const bearerValue = proxyToken
    ? `Bearer ${proxyToken}`
    : "Bearer ${MCP_PROXY_TOKEN}";

  // Normalize transport type — Pi and most MCP clients recognize "sse" and "http",
  // not "streamable-http".
  const piType = proxyType === "streamable-http" ? "http" : proxyType;

  const mcpConfig = {
    mcpServers: {
      [CLI_NAME_LOWERCASE]: {
        type: piType,
        url: `${proxyEndpoint}${pathSuffix}`,
        headers: {
          Authorization: bearerValue,
        },
      },
    },
  };

  return JSON.stringify(mcpConfig, null, 2);
}

/**
 * Generate .pi/extensions/{name}-mcp/package.json content.
 */
function generateExtensionPackageJson(): string {
  return JSON.stringify(
    {
      name: `${CLI_NAME_LOWERCASE}-mcp`,
      version: "1.0.0",
      type: "module",
      main: "index.ts",
    },
    null,
    2,
  );
}

/**
 * Generate .pi/extensions/{name}-mcp/index.ts content.
 *
 * Creates a pi extension that:
 * 1. Registers each task as a pi command (slash commands).
 * 2. On session_start, connects to the mason proxy as an MCP client,
 *    discovers available tools, and registers each one via pi.registerTool()
 *    so the LLM can call them.
 */
function generateExtensionIndexTs(
  agent: ResolvedAgent,
  proxyEndpoint: string,
  proxyType: "sse" | "streamable-http",
): string {
  const mcpPath = proxyType === "sse" ? "/sse" : "/mcp";
  const proxyUrl = `${proxyEndpoint}${mcpPath}`;

  // Build task command registrations
  const commandRegistrations: string[] = [];
  const allTasks = collectAllTasks(agent.roles);
  for (const [task] of allTasks) {
    const taskShortName = getAppShortName(task.name);
    const commandName = task.scope ? `${task.scope}-${taskShortName}` : taskShortName;
    const description = `${task.name}@${task.version}`;
    const rawPrompt = task.prompt ?? "[no prompt defined]";
    const prompt = _agentPkg.mcpNameTemplate
      ? convertMcpFormat(rawPrompt, _agentPkg.mcpNameTemplate)
      : rawPrompt;

    const safeName = commandName.replace(/"/g, '\\"');
    const safeDesc = description.replace(/\\/g, "\\\\").replace(/"/g, '\\"');

    commandRegistrations.push(`
  pi.registerCommand("${safeName}", {
    description: "${safeDesc}",
    handler: async (args, ctx) => {
      pi.sendUserMessage(\`${escapeTemplateLiteral(prompt)}\`);
    },
  });`);
  }

  return `// Generated by the ${CLI_NAME_LOWERCASE} pi-coding-agent materializer

// -- MCP Client ---------------------------------------------------
const PROXY_URL = ${JSON.stringify(proxyUrl)};
let _mcpSessionId = null;
let _reqId = 1;

async function mcpRequest(method, params) {
  const token = process.env.MCP_PROXY_TOKEN;
  if (!token) throw new Error("MCP_PROXY_TOKEN not set");

  const headers = {
    "Content-Type": "application/json",
    "Accept": "application/json, text/event-stream",
    "Authorization": "Bearer " + token,
  };
  if (_mcpSessionId) headers["mcp-session-id"] = _mcpSessionId;

  const isNotification = method.startsWith("notifications/");
  const body = { jsonrpc: "2.0", method, params };
  if (!isNotification) body.id = _reqId++;

  const res = await fetch(PROXY_URL, {
    method: "POST",
    headers,
    body: JSON.stringify(body),
  });

  if (!res.ok) throw new Error("MCP " + method + " failed: " + res.status);
  if (method === "initialize") {
    _mcpSessionId = res.headers.get("mcp-session-id");
  }
  if (isNotification) return null;

  // Parse JSON or SSE response
  const ct = res.headers.get("content-type") || "";
  if (ct.includes("text/event-stream")) {
    const text = await res.text();
    let last = "";
    for (const line of text.split("\\n")) {
      if (line.startsWith("data: ")) last = line.slice(6);
    }
    return last ? JSON.parse(last) : null;
  }
  return res.json();
}

// -- Discover MCP tools at module load (top-level await) ----------
let _mcpTools = [];
try {
  await mcpRequest("initialize", {
    protocolVersion: "2025-03-26",
    capabilities: {},
    clientInfo: { name: "${CLI_NAME_LOWERCASE}-pi-extension", version: "0.1.0" },
  });
  await mcpRequest("notifications/initialized", {});
  const listRes = await mcpRequest("tools/list", {});
  _mcpTools = listRes?.result?.tools || [];
  console.error("[${CLI_NAME_LOWERCASE}] Discovered " + _mcpTools.length + " MCP tools from proxy");
} catch (err) {
  console.error("[${CLI_NAME_LOWERCASE}] Failed to discover MCP tools:", err);
}

// -- Extension ----------------------------------------------------
export default (pi) => {
  // Task commands${commandRegistrations.join("")}

  // Register MCP tools synchronously so Pi picks them up
  for (const tool of _mcpTools) {
    pi.registerTool({
      name: tool.name,
      label: tool.name,
      description: tool.description || "",
      parameters: tool.inputSchema || { type: "object", properties: {} },
      async execute(toolCallId, params) {
        const callRes = await mcpRequest("tools/call", {
          name: tool.name,
          arguments: params,
        });
        const content = callRes?.result?.content || [];
        return {
          content: content.map((c) =>
            c.type === "image"
              ? { type: "image", data: c.data, mimeType: c.mimeType }
              : { type: "text", text: c.text ?? JSON.stringify(c) }
          ),
          details: {},
        };
      },
    });
  }

  if (_mcpTools.length > 0) {
    console.error("[${CLI_NAME_LOWERCASE}] Registered " + _mcpTools.length + " MCP tools");
  }
};
`;
}

/** Reference to the parent AgentPackage — set after construction. */
let _agentPkg: AgentPackage;

export const piCodingAgentMaterializer: RuntimeMaterializer = {
  name: "pi-coding-agent",

  materializeWorkspace(
    agent: ResolvedAgent,
    proxyEndpoint: string,
    proxyToken?: string,
    options?: MaterializeOptions,
  ): MaterializationResult {
    const result: MaterializationResult = new Map();

    // .pi/settings.json — model configuration
    result.set(".pi/settings.json", generatePiSettingsJson(agent));

    // .pi/mcp.json — MCP server config
    const proxyType = agent.proxy?.type ?? "sse";
    result.set(
      ".pi/mcp.json",
      generatePiMcpJson(proxyEndpoint, proxyType, proxyToken),
    );

    // .pi/extensions/{name}-mcp/package.json
    result.set(
      `.pi/extensions/${CLI_NAME_LOWERCASE}-mcp/package.json`,
      generateExtensionPackageJson(),
    );

    // .pi/extensions/{name}-mcp/index.ts — task commands + MCP client
    result.set(
      `.pi/extensions/${CLI_NAME_LOWERCASE}-mcp/index.ts`,
      generateExtensionIndexTs(agent, proxyEndpoint, proxyType),
    );

    // Skills — copy actual SKILL.md + companions via materializeSkills
    if (_agentPkg.skills) {
      const allSkills = collectAllSkills(agent.roles);
      const skillFiles = materializeSkills([...allSkills.values()], _agentPkg.skills, _agentPkg.mcpNameTemplate);
      for (const [p, c] of skillFiles) result.set(p, c);
    }

    // .pi/APPEND_SYSTEM.md — role instructions into system prompt
    const instructions = agent.roles[0]?.instructions;
    if (instructions) {
      result.set(".pi/APPEND_SYSTEM.md", instructions);
    }

    // .pi/prompts/ — task markdown files
    if (_agentPkg.tasks) {
      const allTasks = collectAllTasks(agent.roles);
      const taskFiles = materializeTasks(allTasks.map(([t]) => t), _agentPkg.tasks, _agentPkg.mcpNameTemplate);
      for (const [p, c] of taskFiles) result.set(p, c);
    }

    // agent-launch.json — tells agent-entry how to bootstrap this agent
    result.set(
      "agent-launch.json",
      generateAgentLaunchJson(_agentPkg, agent.credentials, options?.acpMode, undefined, options?.agentArgs, options?.initialPrompt, options?.printMode),
    );

    return result;
  },
};

/**
 * Set the parent AgentPackage reference (called during package initialization).
 * @internal
 */
export function _setAgentPackage(pkg: AgentPackage): void {
  _agentPkg = pkg;
}
