/**
 * ACP Session — Docker Session Orchestration for ACP
 *
 * Manages the three-container Docker Compose session (proxy + credential-service
 * + agent) for ACP mode. Adapts the existing `run-agent.ts` pattern for
 * programmatic lifecycle management (start/stop instead of interactive).
 *
 * PRD refs: REQ-005 (Docker Session Lifecycle)
 */

import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import {
  readRunConfig,
  validateDockerfiles,
  execComposeCommand,
  generateSessionId,
} from "../cli/commands/run-agent.js";
import { checkDockerCompose } from "../cli/commands/docker-utils.js";

// ── Types ─────────────────────────────────────────────────────────────

export interface AcpSessionConfig {
  /** Workspace root directory (must contain .clawmasons/chapter.json) */
  projectDir: string;
  /** Agent short name (e.g., "note-taker") */
  agent: string;
  /** Role short name (e.g., "writer") */
  role: string;
  /** ACP agent port inside the container (default: 3002) */
  acpPort?: number;
  /** Internal proxy port (default: 3000) */
  proxyPort?: number;
  /** Session credential overrides extracted from ACP client mcpServers */
  credentials?: Record<string, string>;
}

export interface SessionInfo {
  /** Unique session identifier */
  sessionId: string;
  /** Path to session directory */
  sessionDir: string;
  /** Path to generated docker-compose.yml */
  composeFile: string;
  /** ACP port exposed on the host */
  acpPort: number;
  /** Name of the proxy service in compose */
  proxyServiceName: string;
  /** Name of the agent service in compose */
  agentServiceName: string;
}

/**
 * Dependencies for AcpSession, injectable for testing.
 */
export interface AcpSessionDeps {
  /** Override the compose command executor (for testing). */
  execComposeFn?: (
    composeFile: string,
    args: string[],
    opts?: { interactive?: boolean },
  ) => Promise<number>;
  /** Override session ID generation (for testing). */
  generateSessionIdFn?: () => string;
  /** Override docker compose check (for testing). */
  checkDockerComposeFn?: () => void;
}

// ── Compose Generation ────────────────────────────────────────────────

/**
 * Generate a docker-compose.yml for an ACP session.
 *
 * Differences from the standard run-agent compose:
 * - Agent container is non-interactive (no stdin_open/tty)
 * - Agent container exposes ACP port to the host
 * - Credential-service gets CREDENTIAL_SESSION_OVERRIDES env var
 */
export function generateAcpComposeYml(opts: {
  dockerBuildPath: string;
  projectDir: string;
  agent: string;
  role: string;
  logsDir: string;
  proxyToken: string;
  credentialProxyToken: string;
  acpPort: number;
  credentials?: Record<string, string>;
}): string {
  const {
    dockerBuildPath,
    projectDir,
    agent,
    role,
    logsDir,
    proxyToken,
    credentialProxyToken,
    acpPort,
    credentials,
  } = opts;

  const proxyContext = dockerBuildPath;
  const proxyDockerfile = path.join("proxy", role, "Dockerfile");
  const agentContext = dockerBuildPath;
  const agentDockerfile = path.join("agent", agent, role, "Dockerfile");
  const credentialServiceDockerfile = path.join("credential-service", "Dockerfile");

  const proxyServiceName = `proxy-${role}`;
  const agentServiceName = `agent-${agent}-${role}`;

  // Build credential-service environment lines
  const credentialEnvLines = [`      - CREDENTIAL_PROXY_TOKEN=${credentialProxyToken}`];
  if (credentials && Object.keys(credentials).length > 0) {
    const overridesJson = JSON.stringify(credentials);
    credentialEnvLines.push(`      - CREDENTIAL_SESSION_OVERRIDES=${overridesJson}`);
  }

  return `# Generated by chapter acp-session
services:
  ${proxyServiceName}:
    build:
      context: "${proxyContext}"
      dockerfile: "${proxyDockerfile}"
    volumes:
      - "${projectDir}:/workspace"
      - "${logsDir}:/logs"
    environment:
      - CHAPTER_PROXY_TOKEN=${proxyToken}
      - CREDENTIAL_PROXY_TOKEN=${credentialProxyToken}
    restart: "no"

  credential-service:
    build:
      context: "${proxyContext}"
      dockerfile: "${credentialServiceDockerfile}"
    environment:
${credentialEnvLines.join("\n")}
    depends_on:
      - ${proxyServiceName}
    restart: "no"

  ${agentServiceName}:
    build:
      context: "${agentContext}"
      dockerfile: "${agentDockerfile}"
    volumes:
      - "${projectDir}:/workspace"
    depends_on:
      - credential-service
    environment:
      - MCP_PROXY_TOKEN=${proxyToken}
    ports:
      - "${acpPort}:${acpPort}"
    init: true
    restart: "no"
`;
}

// ── AcpSession ────────────────────────────────────────────────────────

export class AcpSession {
  private readonly config: AcpSessionConfig;
  private readonly deps: Required<AcpSessionDeps>;
  private running = false;
  private sessionInfo: SessionInfo | null = null;

  constructor(config: AcpSessionConfig, deps?: AcpSessionDeps) {
    this.config = config;
    this.deps = {
      execComposeFn: deps?.execComposeFn ?? execComposeCommand,
      generateSessionIdFn: deps?.generateSessionIdFn ?? generateSessionId,
      checkDockerComposeFn: deps?.checkDockerComposeFn ?? checkDockerCompose,
    };
  }

  /**
   * Start the ACP Docker session.
   *
   * Generates a docker-compose.yml and starts all three services in detached
   * mode. Returns session info including paths and port assignments.
   *
   * @throws If the session is already running, Docker is unavailable,
   *         Dockerfiles are missing, or compose up fails.
   */
  async start(): Promise<SessionInfo> {
    if (this.running) {
      throw new Error("ACP session is already running");
    }

    const { projectDir, agent, role } = this.config;
    const acpPort = this.config.acpPort ?? 3002;

    // Pre-flight checks
    this.deps.checkDockerComposeFn();

    const runConfig = readRunConfig(projectDir);
    const dockerBuildPath = runConfig["docker-build"];
    validateDockerfiles(dockerBuildPath, agent, role);

    // Generate session directory
    const sessionId = this.deps.generateSessionIdFn();
    const sessionDir = path.join(projectDir, ".clawmasons", "sessions", sessionId, "docker");
    fs.mkdirSync(sessionDir, { recursive: true });

    const logsDir = path.join(projectDir, ".clawmasons", "logs");
    fs.mkdirSync(logsDir, { recursive: true });

    // Generate tokens
    const proxyToken = crypto.randomBytes(32).toString("hex");
    const credentialProxyToken = crypto.randomBytes(32).toString("hex");

    // Generate compose file
    const composeContent = generateAcpComposeYml({
      dockerBuildPath,
      projectDir,
      agent,
      role,
      logsDir,
      proxyToken,
      credentialProxyToken,
      acpPort,
      credentials: this.config.credentials,
    });

    const composeFile = path.join(sessionDir, "docker-compose.yml");
    fs.writeFileSync(composeFile, composeContent);

    // Start all services detached
    const exitCode = await this.deps.execComposeFn(composeFile, ["up", "-d"]);
    if (exitCode !== 0) {
      throw new Error(`Failed to start ACP session (docker compose exit code ${exitCode})`);
    }

    const proxyServiceName = `proxy-${role}`;
    const agentServiceName = `agent-${agent}-${role}`;

    this.sessionInfo = {
      sessionId,
      sessionDir,
      composeFile,
      acpPort,
      proxyServiceName,
      agentServiceName,
    };

    this.running = true;
    return this.sessionInfo;
  }

  /**
   * Stop the ACP Docker session.
   *
   * Tears down all containers via `docker compose down`. Idempotent --
   * calling stop when not running is a no-op.
   */
  async stop(): Promise<void> {
    if (!this.running || !this.sessionInfo) {
      return;
    }

    await this.deps.execComposeFn(this.sessionInfo.composeFile, ["down"]);
    this.running = false;
  }

  /**
   * Check if the session is currently running.
   */
  isRunning(): boolean {
    return this.running;
  }
}
